#!/usr/bin/env python3
"""Build manifest.json: every load-bearing claim -> the artifact that supports it."""
import json,os,hashlib,glob,datetime
B='/home/user/dd1/incident-intelligence'
def sha(p):
    try: return hashlib.sha256(open(p,'rb').read()).hexdigest()
    except Exception: return None
def ent(rel,role,claim):
    p=os.path.join(B,rel)
    return {"path":rel,"exists":os.path.exists(p),
            "bytes":os.path.getsize(p) if os.path.exists(p) else 0,
            "sha256":sha(p),"role":role,"supports_claim":claim}
crawl=json.load(open(f'{B}/sources/slowmist/crawl_log_all.json'))
dlm=json.load(open(f'{B}/sources/defillama/protocols.meta.json'))
M={
 "run_id":json.load(open(f'{B}/run_config.json'))['run_id'],
 "generated_utc":datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'),
 "safety_attestation":{
   "production_transactions_submitted":0,"production_transactions_constructed":0,
   "credentials_recovered_or_used":0,"unauthorized_extraction_optimized":False,
   "chain_access_methods":["eth_call","eth_getStorageAt","eth_getCode","explorer getsourcecode","HTTP GET"],
   "statement":"All production-chain interaction was read-only. No transaction was constructed, signed, simulated as a broadcast against live user state, or submitted. No private key or credential was recovered, derived or used. No exploitation sequence was produced."},
 "primary_sources":{
   "slowmist_index":{"base_url":"https://hacked.slowmist.io/?c=&page=1",
     "pages_fetched":len(crawl['pages']),
     "boundary_status":crawl['pages'][-1]['status'],
     "per_page":[{"page":p['page'],"url":p['url'],"retrieved_utc":p.get('retrieved_utc'),
                  "sha256":p.get('sha256'),"snapshot":f"sources/slowmist/{p.get('snapshot')}" if p.get('snapshot') else None,
                  "rows_parsed":p.get('rows_parsed'),"rows_in_window":p.get('rows_in_window'),
                  "first_date":p.get('first_date'),"last_date":p.get('last_date'),"status":p['status']}
                 for p in crawl['pages']]},
   "defillama_protocols":{**dlm,"snapshot":"sources/defillama/protocols.json"},
   "defillama_adapters_repo":"https://github.com/DefiLlama/DefiLlama-Adapters (raw reads of projects/* and registries/*)"},
 "artifacts":[
  ent("run_config.json","config","Window 2026-02-22..2026-08-22, thresholds, evidence-level definitions"),
  ent("commands.sh","reproduction","Every retrieval and transformation step in execution order"),
  ent("incidents/all_raw.jsonl","incident corpus","240 SlowMist rows; 205 inside the window; every row retained and dispositioned"),
  ent("incidents/included.jsonl","incident corpus","110 grade-A/B on-chain incidents with reconstructed invariants and guards"),
  ent("incidents/provisional.jsonl","incident corpus","22 grade-C incidents; excluded from statistics and ranking weight"),
  ent("incidents/excluded.jsonl","incident corpus","Every exclusion with a concrete reason code from a controlled vocabulary"),
  ent("incidents/duplicate_groups.json","dedup","Clone and repeat lineages; prevents clone incidents inflating independent recurrence"),
  ent("families/families.json","pattern library","43 mechanism families with invariant, mechanism, preconditions, indicators and guards"),
  ent("families/families.md","pattern library","Human-readable family library"),
  ent("families/guard_library.jsonl","guard library","Decisive guards with evidence patterns and limitations"),
  ent("families/near_miss_library.jsonl","guard library","Pairs killed by a precondition or a decisive guard, with residual uncertainty"),
  ent("sources/slowmist/crawl_log_all.json","provenance","Per-page fetch log, hashes and boundary proof"),
  ent("sources/incident-references/reference_index.json","provenance","Every reference URL with retrieval status; social posts marked LEAD_ONLY"),
  ent("sources/defillama/protocols.json","universe","8103 DefiLlama protocol rows, all keys preserved"),
  ent("protocols/defillama_universe.json","universe","Normalized universe with derived feature fields"),
  ent("protocols/eligibility.json","screen","Eligibility decision and sub-threshold high-fit queue per protocol"),
  ent("protocols/pairs_l0.json","screen","All generated protocol-family pairs at L0"),
  ent("protocols/deep_screen_worklist.json","screen","Stratified deep-screen worklist across families and exposure tiers"),
  ent("protocols/adapters_index.json","adapter evidence","Per-protocol adapter read, hashes, addresses, dynamic sources"),
  ent("protocols/registry_configs.json","adapter evidence","Per-protocol configs from registries/compound.js, aave.js, curators.js"),
  ent("protocols/dead_adapters.json","adapter evidence","DefiLlama registries/deadAdapters.json: 591 dead deployments with deadFrom"),
  ent("protocols/onchain_probes.json","live state","Read-only eth_call/eth_getStorageAt/getsourcecode results"),
  ent("protocols/prior_art.json","prior art","Researched prior-art status and documented decisive guards"),
  ent("protocols/conditions.json","screen","Creative observable conditions per protocol: fork-of-victim, dead adapter with residual TVL, version-sibling legacy, declared fallback oracle, RWA pricing surface, co-curated vaults, tag-driven architecture and more"),
  ent("protocols/victim_map.json","screen","In-window incident victims mapped to live DefiLlama slugs, with the families they carry"),
  ent("protocols/subfloor_authority_deferred.json","screen","Authority-bearing protocols below the $50,000 floor: identified, recorded, and deliberately not screened"),
  ent("protocols/registry_configs.json","adapter evidence","Per-protocol configs parsed from registries/compound.js, aave.js and curators.js"),
  ent("protocols/deep_screened.jsonl","scoring","Per-pair precondition gate, guards, MATCH/CONFIDENCE/PREVENTION with components"),
  ent("results/candidates_all.csv","results","Every surviving pair with both ranks and full score components"),
  ent("results/candidates_by_priority.md","results","Ranking A - PRIORITY = likelihood x actionability; the queue to actually work"),
  ent("results/candidates_by_likelihood.md","results","Ranking B - likelihood alone, ignoring whether an independent reviewer can act"),
  ent("results/candidates_by_match.md","results","Ranking C - mechanism match only, no learned component"),
  ent("results/upgrade_authority_exposure.md","results","Custody exposure: terminal upgrade authority per protocol, scored separately from likelihood on the ablation's evidence"),
  ent("sources/defillama/hacks.json","incident evidence","DefiLlama's structured hacks dataset: 1227 incidents with defillamaId, technique and classification"),
  ent("protocols/hazard_tables_v2.json","screen","Empirical chain and category hazard ratios, blended across the SlowMist window corpus and DefiLlama's dataset"),
  ent("protocols/feature_lift_uncensored.json","validation","Per-signal measured lift over the full listed universe, correcting the survivorship censoring"),
  ent("protocols/survivorship_check.json","validation","The censoring test itself: audit rates among victims that fell below the floor versus those still listed"),
  ent("protocols/learned_weights.json","validation","Weights fitted on 2022-24 incidents and validated against 2025-26 incidents, with the temporal split recorded"),
  ent("protocols/ablation.json","validation","Feature-group ablation: which v4 additions actually improved out-of-sample prediction, and which were dropped for failing to"),
  ent("protocols/backtest.json","validation","Leakage-controlled backtest of the production score against known victims"),
  ent("protocols/admin_posture.json","live state","Terminal upgrade/privileged authority per protocol, resolved by walking ERC-1967 admin and owner() chains up to three hops"),
  ent("protocols/authority_exposure.json","live state","Custody exposure rows behind results/upgrade_authority_exposure.md"),
  ent("incidents/source_verification.json","incident evidence","Per-claim verification of INC-2026-08-18-MAY against the project's live public source, plus the THORChain upstream check"),
  ent("results/candidates_by_urgency.md","results","Urgency-first candidate list: ranked by time-to-exploitation with remediation status as the primary driver, Tier 1-2 first, with CORE.md handoff lines"),
  ent("protocols/victim_state.json","scoring","Each recorded victim classified from its TVL series as drained, restored (restore window), or never materially hit"),
  ent("protocols/relatives.json","scoring","Un-hit relatives of victims -- the actual targets -- with the lineage link and the sibling's current holdings"),
  ent("protocols/tvl_head.json","live state","Current TVL for every protocol, re-read at head; the basis of the hard live-value gate"),
  ent("protocols/urgency_pairs.json","scoring","Per-pair tier assignment and URGENCY components (40 remediation gap / 20 recency+propagation / 25 reachable value / 15 precondition match)"),
  ent("protocols/operator_leads.json","incident evidence","Operator-named leads resolved against this run, with window status and what each changes"),
  ent("protocols/cosmos_evm_triage.json","screen","Criteria-based triage of the Cosmos EVM precompile exposure surface; every row carries patch_status NOT_DETERMINED and no chain is asserted unremediated"),
  ent("results/cosmos_evm_exposure.md","results","What the Cosmos EVM precompile cluster corrected, confirmed and changed in this run, with the assessability of each risk archetype stated"),
  ent("protocols/chain_hazard_measured.json","screen","Per-chain hazard measured as incident share over protocol share, with a support floor below which a chain is left UNMEASURED rather than defaulted"),
  ent("protocols/nonevm_cohort.json","screen","Non-EVM protocols above the floor, classified by execution runtime, with the families that structurally apply to each"),
  ent("protocols/appchain_probe.json","live state","Public-source probe of reachable app-chains using app/app.go module discovery"),
  ent("protocols/delivered_ledger.json","delivery","Cumulative ledger of every protocol handed over in a previous run, reconstructed from git history; excluded from this run's candidates"),
  ent("results/nonevm_cohort.md","results","The non-EVM cohort: what the EVM instrument could not see, the Maya verification, the THORChain kill, and an explicit coverage limit"),
  ent("protocols/band_screen.json","screen","Per-protocol band status, empirical hazard, attention deficit and attacker economics"),
  ent("protocols/above_band_dropped.json","screen","Protocols above the $30M band that were dropped, with the reason"),
  ent("results/audit_variables.txt","handoff","One self-contained line per final candidate for the downstream audit prompt"),
  ent("results/excluded_protocols.md","results","Universe exclusions and killed pairs with reasons"),
  ent("results/run_summary.md","results","Required summary statistics"),
  ent("quality_report.md","quality","Mechanical quality gates and known limitations"),
 ],
 "claim_map":{
  "205 incidents inside the six-month window":"incidents/all_raw.jsonl + sources/slowmist/crawl_log_all.json (boundary proven on page 12)",
  "110 included grade-A/B incidents":"incidents/included.jsonl",
  "43 mechanism families":"families/families.json",
  "family incident counts, losses and recency":"families/families.json (computed from incidents/all_raw.jsonl)",
  "clone lineages do not inflate recurrence":"incidents/duplicate_groups.json + families.json unique_root_cause_count",
  "8103 protocols fetched":"sources/defillama/protocols.meta.json",
  "eligibility and sub-threshold high-fit queue":"protocols/eligibility.json",
  "adapter read or marked missing for every candidate":"protocols/adapters_index.json",
  "Compound-fork and curator lineage":"protocols/registry_configs.json (registries/compound.js, curators.js)",
  "deprecated deployment evidence":"protocols/dead_adapters.json + eligibility.json deprecated/deadUrl flags",
  "live-state evidence":"protocols/onchain_probes.json",
  "score components and caps":"protocols/deep_screened.jsonl + results/candidates_all.csv",
  "prior-art status per final pair":"protocols/prior_art.json + results/candidates_by_*.md",
  "out-of-sample validation of the scoring model":"protocols/learned_weights.json (fit 2022-24, tested 2025-26 on 95 unseen protocols)",
  "which features earned their place and which were dropped":"protocols/ablation.json (refit and revalidated per feature group)",
  "survivorship censoring and its correction":"protocols/survivorship_check.json + protocols/feature_lift_uncensored.json",
  "leakage control in the backtest":"protocols/backtest.json (tools/backtest.py --no-prior)",
  "custody exposure measured but kept out of the likelihood score":"protocols/admin_posture.json + results/upgrade_authority_exposure.md + protocols/ablation.json",
  "function selectors used for on-chain fingerprinting":"tools/keccak.py (derived, self-checked against two known selectors at import)",
  "Maya Protocol defect claims verified against live public source":"incidents/source_verification.json (5 of 6 confirmed at exact file and line)",
  "THORChain lineage lead killed on evidence":"incidents/source_verification.json#upstream_check",
  "every candidate is one not handed over before":"protocols/delivered_ledger.json + results/candidates_all.csv#previously_delivered",
  "two in-window incidents the index missed":"incidents/all_raw.jsonl#INC-2026-08-20-MAN, #INC-2026-08-22-TCH (source: OPERATOR_SUPPLIED_THREAT_INTELLIGENCE_REPORT)",
  "Cosmos EVM exposure triaged without asserting patch state":"protocols/cosmos_evm_triage.json + results/cosmos_evm_exposure.md",
  "candidates ranked by time-to-exploitation, not likelihood":"protocols/urgency_pairs.json + results/candidates_by_urgency.md",
  "no remediation gap claimed without an artifact-level check":"protocols/urgency_pairs.json (all rows KNOWN_ISSUE_STATUS_UNKNOWN, 28 of 40)",
  "chain priority measured rather than assumed":"protocols/chain_hazard_measured.json (tools/nonevm_hazard.py)",
  "non-EVM coverage and its limit":"protocols/nonevm_cohort.json + results/nonevm_cohort.md + protocols/appchain_probe.json",
  "runtime families are not applied to runtimes that roll back":"tools/nonevm_cohort.py RUNTIME_FAMILIES + tools/matcher.py RUNTIME_ONLY",
  "near misses":"families/near_miss_library.jsonl",
  "empirical victim profile and hazard ratios":"tools/hazard.py, derived from incidents/included.jsonl + provisional.jsonl",
  "band decisions and why each protocol was kept or dropped":"protocols/band_screen.json + protocols/above_band_dropped.json",
  "creative condition layer":"protocols/conditions.json (definitions in tools/conditions.py)",
  "deployed-source static indicators":"protocols/onchain_probes.json#<slug>.source_sweep + cached source under sources/deployments/",
  "hard $50k floor and what it excluded":"protocols/eligibility.json + protocols/subfloor_authority_deferred.json",
 }}
json.dump(M,open(f'{B}/manifest.json','w'),indent=1)
missing=[a['path'] for a in M['artifacts'] if not a['exists'] or a['bytes']==0]
print(json.dumps({"artifacts":len(M['artifacts']),"missing_or_empty":missing,
 "slowmist_pages":len(crawl['pages']),"claims_mapped":len(M['claim_map'])},indent=2))
