# -*- coding: utf-8 -*-
"""Phase B gate + Phase C/D assignment table.

DISPOSITION: INCLUDE (on-chain defect, grade A/B) | PROVISIONAL (on-chain, grade C)
             | EXCLUDE (off-chain root cause, or gate-passed but evidence grade D)
Tuple = (disposition, grade, reason_code, [family_ids], chains, archetypes)
"""

# ---- controlled exclusion vocabulary -------------------------------------
EXC = {
 "EXC_PRIVATE_KEY":            "Root cause is a stolen/leaked private key or signer credential; contracts behaved as designed.",
 "EXC_CREDENTIAL_COMPROMISE":  "Root cause is compromise of an operator/admin/validator credential or account.",
 "EXC_PHISHING_SOCIAL":        "Root cause is phishing, social engineering or prompt-injection of an operator/user.",
 "EXC_SUPPLY_CHAIN_FRONTEND":  "Root cause is a compromised build/dependency/front-end distribution path.",
 "EXC_DNS_DOMAIN":             "Root cause is DNS/domain/registrar hijack with no independent contract defect.",
 "EXC_INFRA_SERVER":           "Root cause is server/cloud/endpoint/RPC infrastructure compromise.",
 "EXC_EXCHANGE_HOTWALLET":     "Root cause is intrusion into a custodial/exchange/hot-wallet system.",
 "EXC_WALLET_RNG_FIRMWARE":    "Root cause is weak wallet RNG, seed generation or hardware/firmware defect.",
 "EXC_RUG_OR_ADMIN_MISUSE":    "Root cause is rug pull or use of legitimately held administrator authority.",
 "EXC_CAUSE_UNKNOWN":          "Cause remains unknown or undisclosed; no root cause to reconstruct.",
 "EXC_OFFCHAIN_CLIENT_PROTO":  "Root cause is an off-chain client/P2P trade-protocol defect, not on-chain state.",
 "EXC_OFFCHAIN_SIGNING_INFRA": "Root cause is a defect in off-chain signing/threshold-signature infrastructure.",
 "PATTERN_EXC_GRADE_D":        "Gate passed (on-chain defect) but evidence grade D: mechanism vague, contradictory or unsupported. Excluded from pattern derivation only.",
}

# ---- 205 in-window rows --------------------------------------------------
T = {
# --- August 2026 ---
"INC-2026-08-18-MAY": ("INCLUDE","B",None,["ACC-MULTI-PATH-CREDIT-DRIFT"],["THORChain-fork L1","Arbitrum"],["cross-chain liquidity network","AMM","epoch settlement"]),
"INC-2026-08-15-FOX": ("INCLUDE","B",None,["ORACLE-SPOT-THIN-LIQUIDITY"],["BSC"],["bonding/staking","reward distributor","AMM-priced mint"]),
"INC-2026-08-11-HAR": ("PROVISIONAL","C",None,["ACC-SIGN-OR-BOUND-CHECK-MISSING"],["Harmony"],["L1 chain"]),
"INC-2026-08-10-USM": ("INCLUDE","A",None,["ACC-SPLIT-NONINVARIANT"],["Ethereum"],["stablecoin issuer","structured product"]),
"INC-2026-08-09-COI": ("EXCLUDE",None,"EXC_CAUSE_UNKNOWN",[],["Ethereum","Tron"],["payment processor"]),
"INC-2026-08-09-ORA": ("PROVISIONAL","C",None,["BRIDGE-MESSAGE-NOT-BOUND-TO-SOURCE"],["Oraichain","Ethereum"],["bridge","L1 chain"]),
"INC-2026-08-09-COR": ("INCLUDE","B",None,["BRIDGE-MESSAGE-NOT-BOUND-TO-SOURCE"],["Coreum","XRPL"],["bridge"]),
"INC-2026-08-08-ATO": ("INCLUDE","A",None,["SIG-REPLAY-CROSS-POSITION"],["Arbitrum"],["liquidity manager","leveraged trading"]),
"INC-2026-08-06-RRW": ("EXCLUDE",None,"EXC_WALLET_RNG_FIRMWARE",[],["multi"],["wallet"]),
"INC-2026-08-06-UNI": ("INCLUDE","B",None,["CALLDATA-CALLER-CONTROLLED-TARGET"],["Ethereum"],["token launch platform","liquidity manager"]),
"INC-2026-08-06-KIT": ("EXCLUDE",None,"EXC_PRIVATE_KEY",[],["Ethereum"],["token"]),
"INC-2026-08-05-ZEU": ("EXCLUDE",None,"EXC_INFRA_SERVER",[],["Bitcoin/Lightning"],["wallet/LSP"]),
"INC-2026-08-03-RIS": ("PROVISIONAL","C",None,["AUTH-MISSING-ON-VALUE-MOVING-PATH"],["Ethereum"],["RWA strategy","vault"]),
"INC-2026-08-02-LOO": ("INCLUDE","B",None,["ORACLE-SPOT-THIN-LIQUIDITY","SETTLEMENT-EPOCH-BOUNDARY-CREDIT"],["BSC"],["lending/interest-bearing","reward distributor"]),
"INC-2026-08-02-MOK": ("INCLUDE","A",None,["AUTH-PUBLIC-CLAIM-NO-ELIGIBILITY"],["BSC"],["token","reward distributor"]),
"INC-2026-07-30-COL": ("EXCLUDE",None,"EXC_WALLET_RNG_FIRMWARE",[],["Bitcoin"],["hardware wallet"]),
"INC-2026-07-30-SET": ("INCLUDE","B",None,["CALLBACK-STATE-LOCK-INCOMPLETE"],["Ethereum"],["indexes","structured product"]),
"INC-2026-07-30-SWA": ("INCLUDE","B",None,["SECRET-EMBEDDED-IN-PUBLIC-CODE-AS-AUTH"],["BSC"],["asset management","token sale"]),
"INC-2026-07-28-CRY": ("INCLUDE","B",None,["AUTH-MISSING-ON-VALUE-MOVING-PATH"],["BSC"],["token","vault"]),
"INC-2026-07-28-LUL": ("INCLUDE","B",None,["TOKEN-DEFERRED-BURN-LP-RESERVE-DESYNC"],["BSC"],["token"]),
"INC-2026-07-26-WEM": ("EXCLUDE",None,"EXC_PRIVATE_KEY",[],["WEMIX"],["stablecoin issuer"]),
"INC-2026-07-26-GAR": ("EXCLUDE",None,"EXC_INFRA_SERVER",[],["Ethereum","Base","Arbitrum","BSC"],["bridge/HTLC"]),
"INC-2026-07-26-CHA": ("EXCLUDE",None,"EXC_CREDENTIAL_COMPROMISE",[],["Ethereum","BSC","Avalanche","Polygon"],["bridge"]),
"INC-2026-07-25-BAN": ("EXCLUDE",None,"EXC_CREDENTIAL_COMPROMISE",[],["Base"],["agent wallet"]),
"INC-2026-07-25-PRO": ("INCLUDE","A",None,["ACC-CREDIT-NOT-RECEIVED"],["Ethereum"],["reward distributor","vault"]),
"INC-2026-07-24-LIE": ("INCLUDE","B",None,["ACC-SPLIT-NONINVARIANT"],["Ethereum"],["structured product","options"]),
"INC-2026-07-24-TRI": ("EXCLUDE",None,"EXC_EXCHANGE_HOTWALLET",[],["multi"],["payments"]),
"INC-2026-07-23-VER": ("INCLUDE","A",None,["BRIDGE-MESSAGE-NOT-BOUND-TO-SOURCE"],["Ethereum","Verus"],["bridge"]),
"INC-2026-07-23-SOL": ("INCLUDE","A",None,["ORACLE-STALE-OR-SILENT-FALLBACK"],["Supra"],["CDP","lending","stablecoin issuer"]),
"INC-2026-07-22-AFX": ("EXCLUDE",None,"EXC_PRIVATE_KEY",[],["Arbitrum","Ethereum"],["bridge"]),
"INC-2026-07-22-42D": ("INCLUDE","B",None,["LIQUIDATION-ON-MANIPULABLE-VALUATION"],["BSC"],["CDP","stablecoin issuer","lending"]),
"INC-2026-07-21-FLA": ("EXCLUDE",None,"EXC_CAUSE_UNKNOWN",[],["Solana"],["derivatives"]),
"INC-2026-07-21-WAN": ("EXCLUDE",None,"PATTERN_EXC_GRADE_D",[],["Cardano","BSC"],["bridge"]),
"INC-2026-07-19-ALL": ("INCLUDE","B",None,["AMM-POOL-RATIO-SKEW-EXTRACTION"],["Solana"],["bridge","DEX/AMM"]),
"INC-2026-07-19-ZIL": ("EXCLUDE",None,"EXC_WALLET_RNG_FIRMWARE",[],["Zilliqa"],["wallet app"]),
"INC-2026-07-17-ACR": ("INCLUDE","B",None,["BRIDGE-MESSAGE-NOT-BOUND-TO-SOURCE"],["Solana"],["bridge","intents relayer"]),
"INC-2026-07-16-DEF": ("EXCLUDE",None,"PATTERN_EXC_GRADE_D",[],["Solana"],["lending"]),
"INC-2026-07-15-OST": ("PROVISIONAL","C",None,["ORACLE-STALE-OR-SILENT-FALLBACK"],["Arbitrum"],["derivatives","RWA perps"]),
"INC-2026-07-15-TEL": ("EXCLUDE",None,"EXC_CAUSE_UNKNOWN",[],["Bitcoin","BSC"],["bridge"]),
"INC-2026-07-15-BAR": ("INCLUDE","B",None,["GOV-CHEAP-CONTROL-NO-TIMELOCK","APPROVALS-TO-UPGRADEABLE-SPENDER"],["Ethereum"],["governance-controlled proxy","structured product"]),
"INC-2026-07-15-CAS": ("INCLUDE","B",None,["LIQUIDATION-ON-MANIPULABLE-VALUATION"],["Arbitrum"],["derivatives","perpetuals"]),
"INC-2026-07-14-DRI": ("INCLUDE","A",None,["ACC-SIGN-OR-BOUND-CHECK-MISSING"],["Ethereum"],["streaming payments"]),
"INC-2026-07-13-LUM": ("INCLUDE","B",None,["CALLBACK-UNAUTHENTICATED-CALLER-USES-APPROVALS"],["Arbitrum"],["account abstraction","lending"]),
"INC-2026-07-13-CHI": ("INCLUDE","A",None,["ACC-HARDCODED-PEG-REDEMPTION"],["Ethereum"],["stablecoin issuer","CDP"]),
"INC-2026-07-11-BON": ("INCLUDE","B",None,["ORACLE-SPOT-THIN-LIQUIDITY"],["Hedera"],["lending"]),
"INC-2026-07-06-LAZ": ("INCLUDE","A",None,["ACC-NAV-SHAREPRICE-MANIPULABLE","ACC-DONATION-UNACCOUNTED-BALANCE"],["Ethereum"],["yield aggregator","vault/share token","risk curator"]),
"INC-2026-07-06-BON": ("INCLUDE","B",None,["GOV-CHEAP-CONTROL-NO-TIMELOCK"],["Solana"],["DAO treasury"]),
"INC-2026-07-02-HIN": ("INCLUDE","B",None,["PROOF-VERIFICATION-BYPASSED"],["Ethereum"],["privacy pool"]),
"INC-2026-07-01-EDE": ("INCLUDE","B",None,["ORACLE-VAULT-SHARE-RATE-AS-SPOT-PRICE","ACC-NAV-SHAREPRICE-MANIPULABLE"],["Ethereum"],["lending","RWA strategy"]),
"INC-2026-06-28-AID": ("INCLUDE","B",None,["TOKEN-TRANSFER-OVERRIDE-BREAKS-CONSERVATION"],["BSC"],["token"]),
"INC-2026-06-25-POL": ("EXCLUDE",None,"EXC_SUPPLY_CHAIN_FRONTEND",[],["Polygon","Ethereum"],["prediction market"]),
"INC-2026-06-25-LIX": ("INCLUDE","A",None,["SIG-VERIFIER-DEFEATABLE"],["Ethereum"],["liquidity manager","vault/share token"]),
"INC-2026-06-24-YIE": ("EXCLUDE",None,"EXC_SUPPLY_CHAIN_FRONTEND",[],["Avalanche"],["yield aggregator"]),
"INC-2026-06-23-SEC": ("EXCLUDE",None,"EXC_WALLET_RNG_FIRMWARE",[],["Cardano"],["wallet"]),
"INC-2026-06-23-ROY": ("INCLUDE","B",None,["HOOK-ZERO-VALUE-TRANSFER-TRIGGERS-ACCRUAL"],["Polygon"],["reward distributor","NFT royalties"]),
"INC-2026-06-21-GIT": ("EXCLUDE",None,"EXC_SUPPLY_CHAIN_FRONTEND",[],["Ethereum"],["grants platform"]),
"INC-2026-06-21-TAI": ("PROVISIONAL","C",None,["PROOF-VERIFICATION-BYPASSED"],["Ethereum","Taiko"],["canonical bridge","L2"]),
"INC-2026-06-21-QUI": ("INCLUDE","B",None,["PROOF-VERIFICATION-BYPASSED"],["Cosmos/Quicksilver"],["liquid staking"]),
"INC-2026-06-20-MEV": ("PROVISIONAL","C",None,["CALLDATA-CALLER-CONTROLLED-TARGET"],["Ethereum"],["MEV bot"]),
"INC-2026-06-20-LAB": ("INCLUDE","B",None,["TOKEN-DEFERRED-BURN-LP-RESERVE-DESYNC"],["BSC"],["token"]),
"INC-2026-06-19-NAM": ("PROVISIONAL","C",None,["BRIDGE-MESSAGE-NOT-BOUND-TO-SOURCE"],["Namada"],["privacy pool","IBC"]),
"INC-2026-06-19-MYS": ("EXCLUDE",None,"PATTERN_EXC_GRADE_D",[],["Starknet"],["DEX/AMM"]),
"INC-2026-06-19-JBX": ("INCLUDE","B",None,["TOKEN-DEFERRED-BURN-LP-RESERVE-DESYNC"],["BSC"],["token"]),
"INC-2026-06-17-AZT": ("INCLUDE","B",None,["UPGRADE-OLD-DEPLOYMENT-LIVE-AUTHORITY","PROOF-VERIFICATION-BYPASSED"],["Ethereum"],["bridge","rollup"]),
"INC-2026-06-17-LIT": ("INCLUDE","A",None,["HOOK-ZERO-VALUE-TRANSFER-TRIGGERS-ACCRUAL","TOKEN-DEFERRED-BURN-LP-RESERVE-DESYNC"],["BSC"],["farm","token"]),
"INC-2026-06-17-DIP": ("INCLUDE","B",None,["TOKEN-TRANSFER-OVERRIDE-BREAKS-CONSERVATION"],["BSC"],["token"]),
"INC-2026-06-15-THE": ("INCLUDE","B",None,["ACC-ZERO-SUPPLY-INFLATION","UPGRADE-OLD-DEPLOYMENT-LIVE-AUTHORITY"],["Ethereum"],["options","vault/share token"]),
"INC-2026-06-14-AZT": ("INCLUDE","B",None,["PROOF-VERIFICATION-BYPASSED","UPGRADE-OLD-DEPLOYMENT-LIVE-AUTHORITY"],["Ethereum"],["bridge","rollup"]),
"INC-2026-06-10-RAY": ("INCLUDE","A",None,["ASSET-OR-MARKET-IDENTITY-NOT-VALIDATED","UPGRADE-OLD-DEPLOYMENT-LIVE-AUTHORITY"],["Solana"],["DEX/AMM"]),
"INC-2026-06-10-SEC": ("INCLUDE","A",None,["BRIDGE-MESSAGE-NOT-BOUND-TO-SOURCE"],["Secret","Axelar","Osmosis"],["bridge","IBC"]),
"INC-2026-06-09-HUM": ("EXCLUDE",None,"EXC_PRIVATE_KEY",[],["Ethereum"],["identity protocol"]),
"INC-2026-06-09-AST": ("INCLUDE","B",None,["TOKEN-PACKED-OWNERSHIP-UNDERFLOW"],["Ethereum"],["NFT liquidity","token"]),
"INC-2026-06-09-HAE": ("INCLUDE","B",None,["ACC-MULTI-PATH-CREDIT-DRIFT","UPGRADE-OLD-DEPLOYMENT-LIVE-AUTHORITY"],["Sui"],["liquid staking","vault/share token"]),
"INC-2026-06-09-NOV": ("INCLUDE","B",None,["ACC-REWARD-INDEX-INIT-AND-ORDERING"],["Ethereum"],["reward distributor","staking pool"]),
"INC-2026-06-09-TOK": ("INCLUDE","A",None,["GOV-CHEAP-CONTROL-NO-TIMELOCK"],["Ethereum"],["governance-controlled proxy","token"]),
"INC-2026-06-08-SYS": ("PROVISIONAL","C",None,["BRIDGE-MESSAGE-NOT-BOUND-TO-SOURCE"],["Syscoin","Ethereum"],["bridge"]),
"INC-2026-06-08-FLO": ("INCLUDE","A",None,["TOKEN-PACKED-OWNERSHIP-UNDERFLOW"],["Ethereum"],["NFT liquidity","token"]),
"INC-2026-06-08-AMB": ("INCLUDE","B",None,["ACC-MULTI-PATH-CREDIT-DRIFT"],["Ethereum"],["DEX/AMM"]),
"INC-2026-06-08-OPE": ("EXCLUDE",None,"EXC_INFRA_SERVER",[],["Monero"],["P2P platform"]),
"INC-2026-06-05-DTX": ("INCLUDE","B",None,["TOKEN-TRANSFER-INTENT-HEURISTIC-FORGEABLE"],["BSC"],["token"]),
"INC-2026-06-04-ATM": ("INCLUDE","B",None,["TOKEN-TRANSFER-OVERRIDE-BREAKS-CONSERVATION"],["BSC"],["token"]),
"INC-2026-06-04-BYT": ("INCLUDE","A",None,["TOKEN-DEFERRED-BURN-LP-RESERVE-DESYNC"],["BSC"],["token"]),
"INC-2026-06-03-APE": ("INCLUDE","A",None,["ACC-DUPLICATE-ID-ACCUMULATION"],["BSC"],["farm","vote-escrow"]),
"INC-2026-06-01-GNO": ("EXCLUDE",None,"PATTERN_EXC_GRADE_D",[],["Gnosis"],["smart account module"]),
"INC-2026-06-01-THE": ("EXCLUDE",None,"EXC_PHISHING_SOCIAL",[],["multi"],["n/a"]),
"INC-2026-06-01-TES": ("EXCLUDE",None,"EXC_PRIVATE_KEY",[],["BSC"],["token"]),
"INC-2026-06-01-ATO": ("INCLUDE","A",None,["STORAGE-LAYOUT-COLLISION-PHANTOM-CREDIT"],["Ethereum"],["reward distributor","AMM hook"]),
"INC-2026-05-31-FLU": ("EXCLUDE",None,"EXC_PRIVATE_KEY",[],["Ethereum"],["lending","reward distributor"]),
"INC-2026-05-31-PHA": ("EXCLUDE",None,"EXC_INFRA_SERVER",[],["Phala"],["cloud/TEE"]),
"INC-2026-05-30-GRA": ("EXCLUDE",None,"EXC_PRIVATE_KEY",[],["Ethereum","Cosmos"],["bridge"]),
"INC-2026-05-30-ALE": ("EXCLUDE",None,"EXC_INFRA_SERVER",[],["Ethereum","BSC","Alephium"],["bridge"]),
"INC-2026-05-30-ARO": ("EXCLUDE",None,"PATTERN_EXC_GRADE_D",[],["BSC"],["token"]),
"INC-2026-05-29-MON": ("INCLUDE","A",None,["SIG-VERIFIER-DEFEATABLE"],["BSC"],["NFT staking","reward distributor"]),
"INC-2026-05-29-YSD": ("PROVISIONAL","C",None,["TOKEN-DEFERRED-BURN-LP-RESERVE-DESYNC"],["BSC"],["token"]),
"INC-2026-05-28-JOE": ("INCLUDE","A",None,["CALLBACK-STATE-LOCK-INCOMPLETE"],["BSC"],["farm","liquidity manager"]),
"INC-2026-05-28-DXS": ("EXCLUDE",None,"EXC_RUG_OR_ADMIN_MISUSE",[],["BSC"],["launchpad","liquidity locker"]),
"INC-2026-05-28-ONT": ("INCLUDE","A",None,["AUTH-ZERO-ADDRESS-ACCEPTED"],["Ethereum"],["token"]),
"INC-2026-05-27-STA": ("EXCLUDE",None,"EXC_PRIVATE_KEY",[],["Arbitrum"],["liquid staking","bridge/OFT"]),
"INC-2026-05-27-SUP": ("EXCLUDE",None,"EXC_CREDENTIAL_COMPROMISE",[],["BSC"],["token"]),
"INC-2026-05-26-SKP": ("INCLUDE","B",None,["TOKEN-DEFERRED-BURN-LP-RESERVE-DESYNC"],["BSC"],["token"]),
"INC-2026-05-25-WUS": ("INCLUDE","A",None,["INCENTIVE-PER-ADDRESS-NO-SYBIL-COST"],["Ethereum"],["stablecoin issuer","reward distributor"]),
"INC-2026-05-25-THI": ("INCLUDE","A",None,["SECRET-EMBEDDED-IN-PUBLIC-CODE-AS-AUTH","CALLDATA-CALLER-CONTROLLED-TARGET"],["Ethereum","Base"],["smart account module"]),
"INC-2026-05-24-STA": ("EXCLUDE",None,"EXC_CAUSE_UNKNOWN",[],["Ethereum"],["stablecoin issuer"]),
"INC-2026-05-23-MUR": ("INCLUDE","A",None,["AUTH-IDENTITY-SATISFIABLE-BY-ATTACKER-CONTRACT"],["Ethereum"],["reward distributor","payments"]),
"INC-2026-05-22-POL": ("EXCLUDE",None,"EXC_PRIVATE_KEY",[],["Polygon"],["prediction market"]),
"INC-2026-05-22-FRA": ("INCLUDE","A",None,["CALLBACK-STATE-LOCK-INCOMPLETE","SETTLEMENT-EPOCH-BOUNDARY-CREDIT"],["Arbitrum"],["vault/share token","yield"]),
"INC-2026-05-20-BUT": ("INCLUDE","A",None,["SIG-DIGEST-AMBIGUOUS-OR-UNBOUND"],["Ethereum","MAP"],["bridge","cross-chain messaging"]),
"INC-2026-05-20-RET": ("EXCLUDE",None,"EXC_OFFCHAIN_CLIENT_PROTO",[],["Monero"],["P2P DEX"]),
"INC-2026-05-19-BAN": ("EXCLUDE",None,"EXC_PHISHING_SOCIAL",[],["Base"],["agent wallet"]),
"INC-2026-05-19-HER": ("INCLUDE","B",None,["PROOF-VERIFICATION-BYPASSED"],["Algorand"],["privacy pool"]),
"INC-2026-05-18-VER": ("INCLUDE","A",None,["BRIDGE-MESSAGE-NOT-BOUND-TO-SOURCE"],["Ethereum","Verus"],["bridge"]),
"INC-2026-05-18-ECH": ("EXCLUDE",None,"EXC_PRIVATE_KEY",[],["Monad","Ethereum"],["BTC-backed token"]),
"INC-2026-05-17-SEA": ("EXCLUDE",None,"PATTERN_EXC_GRADE_D",[],["Arbitrum"],["token"]),
"INC-2026-05-15-THO": ("EXCLUDE",None,"EXC_OFFCHAIN_SIGNING_INFRA",[],["multi"],["cross-chain liquidity network"]),
"INC-2026-05-15-ADS": ("PROVISIONAL","C",None,["BRIDGE-MESSAGE-NOT-BOUND-TO-SOURCE"],["Ethereum","Adshares"],["bridge"]),
"INC-2026-05-13-TRA": ("PROVISIONAL","C",None,["UPGRADE-OLD-DEPLOYMENT-LIVE-AUTHORITY"],["Tron","Ethereum"],["cross-chain aggregator"]),
"INC-2026-05-13-SHA": ("INCLUDE","B",None,["METATX-SENDER-IDENTITY-CONFUSION"],["Arbitrum"],["DAO treasury","governance"]),
"INC-2026-05-12-AUR": ("INCLUDE","A",None,["UPGRADE-INITIALIZER-REACHABLE-LIVE","APPROVALS-TO-UPGRADEABLE-SPENDER"],["Arbitrum"],["governance-controlled proxy","diamond"]),
"INC-2026-05-12-SQP": ("INCLUDE","B",None,["SECRET-EMBEDDED-IN-PUBLIC-CODE-AS-AUTH"],["BSC"],["staking pool"]),
"INC-2026-05-11-HUM": ("PROVISIONAL","C",None,["UPGRADE-OLD-DEPLOYMENT-LIVE-AUTHORITY"],["Polygon"],["RWA lending"]),
"INC-2026-05-11-INK": ("INCLUDE","B",None,["AUTH-IDENTITY-SATISFIABLE-BY-ATTACKER-CONTRACT"],["Polygon"],["DAO treasury"]),
"INC-2026-05-11-TAC": ("EXCLUDE",None,"EXC_CAUSE_UNKNOWN",[],["TON","Ethereum"],["bridge"]),
"INC-2026-05-11-ROA": ("EXCLUDE",None,"EXC_CREDENTIAL_COMPROMISE",[],["Solana"],["n/a"]),
"INC-2026-05-10-REN": ("INCLUDE","A",None,["UPGRADE-INITIALIZER-REACHABLE-LIVE","UPGRADE-OLD-DEPLOYMENT-LIVE-AUTHORITY"],["Arbitrum"],["dark pool","governance-controlled proxy"]),
"INC-2026-05-07-TRU": ("PROVISIONAL","C",None,["CALLDATA-CALLER-CONTROLLED-TARGET"],["Ethereum"],["RFQ market maker"]),
"INC-2026-05-05-EKU": ("INCLUDE","A",None,["CALLBACK-UNAUTHENTICATED-CALLER-USES-APPROVALS"],["Ethereum"],["DEX/AMM","hook extension"]),
"INC-2026-05-04-SMA": ("EXCLUDE",None,"PATTERN_EXC_GRADE_D",[],["Ethereum"],["leveraged staking"]),
"INC-2026-05-01-BIS": ("EXCLUDE",None,"EXC_OFFCHAIN_CLIENT_PROTO",[],["Bitcoin"],["P2P DEX"]),
"INC-2026-04-30-WAS": ("EXCLUDE",None,"EXC_INFRA_SERVER",[],["Ethereum","Base","Blast","Berachain"],["derivatives","vault"]),
"INC-2026-04-29-SYN": ("EXCLUDE",None,"EXC_PRIVATE_KEY",[],["multi"],["bridge"]),
"INC-2026-04-29-SWE": ("PROVISIONAL","C",None,["AUTH-MISSING-ON-VALUE-MOVING-PATH"],["NEAR"],["token"]),
"INC-2026-04-29-AFT": ("INCLUDE","A",None,["ACC-SIGN-OR-BOUND-CHECK-MISSING"],["Sui"],["derivatives","perpetuals"]),
"INC-2026-04-28-YIE": ("INCLUDE","B",None,["AUTH-MISSING-ON-VALUE-MOVING-PATH"],["Ethereum"],["vault/share token","permissionless listing"]),
"INC-2026-04-28-JUD": ("INCLUDE","B",None,["TOKEN-DEFERRED-BURN-LP-RESERVE-DESYNC"],["BSC"],["token"]),
"INC-2026-04-27-ZET": ("PROVISIONAL","C",None,["CALLDATA-CALLER-CONTROLLED-TARGET"],["Ethereum","BSC","Base","Polygon"],["bridge","cross-chain messaging"]),
"INC-2026-04-27-SIN": ("INCLUDE","A",None,["ORACLE-STALE-OR-SILENT-FALLBACK","ACC-NAV-SHAREPRICE-MANIPULABLE"],["Base"],["vault/share token","yield"]),
"INC-2026-04-26-SCA": ("INCLUDE","A",None,["ACC-REWARD-INDEX-INIT-AND-ORDERING","UPGRADE-OLD-DEPLOYMENT-LIVE-AUTHORITY"],["Sui"],["lending","reward distributor"]),
"INC-2026-04-25-PUR": ("EXCLUDE",None,"EXC_CREDENTIAL_COMPROMISE",[],["HyperEVM","MegaETH"],["lending"]),
"INC-2026-04-23-GID": ("INCLUDE","A",None,["SIG-DIGEST-AMBIGUOUS-OR-UNBOUND"],["Ethereum"],["vault/share token","yield aggregator"]),
"INC-2026-04-22-KIP": ("INCLUDE","A",None,["QUOTE-OR-ROUTE-OUTPUT-NOT-BOUND-TO-ASSET","ASSET-OR-MARKET-IDENTITY-NOT-VALIDATED"],["Base"],["DEX aggregator/router"]),
"INC-2026-04-21-VOL": ("EXCLUDE",None,"EXC_PRIVATE_KEY",[],["Sui"],["vault"]),
"INC-2026-04-20-THE": ("INCLUDE","A",None,["ACC-ZERO-SUPPLY-INFLATION"],["Ethereum"],["options","vault/share token"]),
"INC-2026-04-20-JUI": ("INCLUDE","A",None,["ASSET-OR-MARKET-IDENTITY-NOT-VALIDATED","QUOTE-OR-ROUTE-OUTPUT-NOT-BOUND-TO-ASSET"],["Ethereum"],["token launch platform","lending extension"]),
"INC-2026-04-19-VER": ("EXCLUDE",None,"EXC_SUPPLY_CHAIN_FRONTEND",[],["n/a"],["hosting"]),
"INC-2026-04-19-CUS": ("INCLUDE","A",None,["CALLDATA-CALLER-CONTROLLED-TARGET"],["Avalanche"],["leveraged staking","smart account"]),
"INC-2026-04-18-KEL": ("EXCLUDE",None,"EXC_INFRA_SERVER",[],["Ethereum","multi"],["liquid restaking","cross-chain messaging"]),
"INC-2026-04-18-DNS": ("EXCLUDE",None,"EXC_DNS_DOMAIN",[],["Ethereum"],["gateway"]),
"INC-2026-04-16-RHE": ("INCLUDE","A",None,["QUOTE-OR-ROUTE-OUTPUT-NOT-BOUND-TO-ASSET","ASSET-OR-MARKET-IDENTITY-NOT-VALIDATED"],["NEAR"],["lending","DEX/AMM","leveraged trading"]),
"INC-2026-04-16-GRI": ("EXCLUDE",None,"EXC_EXCHANGE_HOTWALLET",[],["Tron","Ethereum"],["CEX"]),
"INC-2026-04-15-LOO": ("INCLUDE","A",None,["ACC-DUPLICATE-ID-ACCUMULATION"],["Ethereum"],["NFT staking","reward distributor"]),
"INC-2026-04-14-COW": ("EXCLUDE",None,"EXC_DNS_DOMAIN",[],["Ethereum"],["DEX aggregator"]),
"INC-2026-04-13-HYP": ("INCLUDE","B",None,["BRIDGE-MESSAGE-NOT-BOUND-TO-SOURCE"],["Ethereum","Base","BSC","Arbitrum"],["bridge","cross-chain messaging"]),
"INC-2026-04-13-DAN": ("INCLUDE","A",None,["ACC-SIGN-OR-BOUND-CHECK-MISSING"],["Dango","Ethereum"],["derivatives","insurance fund"]),
"INC-2026-04-13-MON": ("INCLUDE","A",None,["TOKEN-DEFERRED-BURN-LP-RESERVE-DESYNC"],["BSC"],["token"]),
"INC-2026-04-12-SUB": ("INCLUDE","A",None,["AUTH-MISSING-ON-VALUE-MOVING-PATH"],["Base"],["staking pool","reward distributor"]),
"INC-2026-04-11-ZER": ("EXCLUDE",None,"EXC_PHISHING_SOCIAL",[],["multi"],["wallet"]),
"INC-2026-04-09-AET": ("PROVISIONAL","C",None,["AUTH-MISSING-ON-VALUE-MOVING-PATH"],["Ethereum","BSC"],["bridge/OFT"]),
"INC-2026-04-07-SQU": ("INCLUDE","A",None,["CALLDATA-CALLER-CONTROLLED-TARGET"],["Ethereum","BSC","Arbitrum","Avalanche"],["bridge","DEX aggregator"]),
"INC-2026-04-07-TGA": ("INCLUDE","B",None,["TOKEN-DEFERRED-BURN-LP-RESERVE-DESYNC"],["BSC"],["token"]),
"INC-2026-04-05-DEN": ("EXCLUDE",None,"PATTERN_EXC_GRADE_D",[],["Linea"],["derivatives"]),
"INC-2026-04-04-BSC": ("INCLUDE","A",None,["TOKEN-DEFERRED-BURN-LP-RESERVE-DESYNC"],["BSC"],["token"]),
"INC-2026-04-03-ADO": ("EXCLUDE",None,"EXC_INFRA_SERVER",[],["n/a"],["n/a"]),
"INC-2026-04-03-HYP": ("EXCLUDE",None,"EXC_DNS_DOMAIN",[],["HyperEVM"],["lending"]),
"INC-2026-04-03-SIL": ("PROVISIONAL","C",None,["ORACLE-STALE-OR-SILENT-FALLBACK"],["Arbitrum"],["lending"]),
"INC-2026-04-03-EIP": ("INCLUDE","A",None,["CALLBACK-UNAUTHENTICATED-CALLER-USES-APPROVALS"],["BSC"],["account abstraction"]),
"INC-2026-04-02-TRU": ("EXCLUDE",None,"EXC_PHISHING_SOCIAL",[],["multi"],["wallet"]),
"INC-2026-04-02-SAS": ("INCLUDE","A",None,["TOKEN-DEFERRED-BURN-LP-RESERVE-DESYNC"],["BSC"],["token"]),
"INC-2026-04-01-DRI": ("EXCLUDE",None,"PATTERN_EXC_GRADE_D",[],["Solana"],["derivatives","vault"]),
"INC-2026-04-01-GAL": ("EXCLUDE",None,"EXC_INFRA_SERVER",[],["n/a"],["CEX/institution"]),
"INC-2026-03-31-ARF": ("EXCLUDE",None,"EXC_CREDENTIAL_COMPROMISE",[],["n/a"],["n/a"]),
"INC-2026-03-31-AXI": ("EXCLUDE",None,"EXC_SUPPLY_CHAIN_FRONTEND",[],["n/a"],["n/a"]),
"INC-2026-03-31-LML": ("INCLUDE","A",None,["ORACLE-STALE-OR-SILENT-FALLBACK","ORACLE-SPOT-THIN-LIQUIDITY"],["BSC"],["staking pool","reward distributor"]),
"INC-2026-03-30-STE": ("EXCLUDE",None,"EXC_DNS_DOMAIN",[],["Ethereum"],["risk curator"]),
"INC-2026-03-28-GOO": ("PROVISIONAL","C",None,["ORACLE-STALE-OR-SILENT-FALLBACK"],["Solana"],["DEX/AMM"]),
"INC-2026-03-26-UNK": ("INCLUDE","B",None,["ORACLE-SPOT-THIN-LIQUIDITY"],["BSC"],["staking pool","reward distributor"]),
"INC-2026-03-24-MOO": ("INCLUDE","B",None,["GOV-CHEAP-CONTROL-NO-TIMELOCK"],["Moonriver"],["lending","governance-controlled proxy"]),
"INC-2026-03-24-LIT": ("EXCLUDE",None,"EXC_SUPPLY_CHAIN_FRONTEND",[],["n/a"],["n/a"]),
"INC-2026-03-23-BCE": ("INCLUDE","B",None,["TOKEN-DEFERRED-BURN-LP-RESERVE-DESYNC"],["BSC"],["token"]),
"INC-2026-03-23-BIT": ("EXCLUDE",None,"EXC_CREDENTIAL_COMPROMISE",[],["Bitcoin"],["ATM operator"]),
"INC-2026-03-22-RES": ("EXCLUDE",None,"EXC_PRIVATE_KEY",[],["Ethereum"],["stablecoin issuer"]),
"INC-2026-03-22-CYR": ("INCLUDE","B",None,["ORACLE-SPOT-THIN-LIQUIDITY"],["BSC"],["yield","liquidity manager"]),
"INC-2026-03-18-NEU": ("EXCLUDE",None,"EXC_DNS_DOMAIN",[],["Ethereum"],["yield"]),
"INC-2026-03-17-DTR": ("INCLUDE","A",None,["ACC-ZERO-SUPPLY-INFLATION"],["Ethereum"],["lending","stablecoin issuer"]),
"INC-2026-03-15-VEN": ("INCLUDE","A",None,["ACC-DONATION-UNACCOUNTED-BALANCE"],["BSC"],["lending"]),
"INC-2026-03-14-GOO": ("INCLUDE","A",None,["ACC-REWARD-INDEX-INIT-AND-ORDERING"],["BSC"],["yield aggregator","farm"]),
"INC-2026-03-12-AMU": ("INCLUDE","B",None,["TOKEN-DEFERRED-BURN-LP-RESERVE-DESYNC"],["BSC"],["token"]),
"INC-2026-03-12-STA": ("INCLUDE","A",None,["BRIDGE-MESSAGE-NOT-BOUND-TO-SOURCE"],["Arbitrum","Ethereum"],["reward distributor","cross-chain messaging"]),
"INC-2026-03-12-AAV": ("INCLUDE","A",None,["ORACLE-STALE-OR-SILENT-FALLBACK","LIQUIDATION-ON-MANIPULABLE-VALUATION"],["Ethereum"],["lending"]),
"INC-2026-03-11-BON": ("EXCLUDE",None,"EXC_DNS_DOMAIN",[],["Solana"],["launchpad"]),
"INC-2026-03-11-DBX": ("INCLUDE","B",None,["METATX-SENDER-IDENTITY-CONFUSION"],["Ethereum"],["token","farm"]),
"INC-2026-03-10-MTW": ("INCLUDE","A",None,["TOKEN-DEFERRED-BURN-LP-RESERVE-DESYNC","TOKEN-TRANSFER-INTENT-HEURISTIC-FORGEABLE"],["BSC"],["token"]),
"INC-2026-03-09-GON": ("INCLUDE","B",None,["AUTH-MISSING-ON-VALUE-MOVING-PATH"],["Ethereum"],["NFT lending"]),
"INC-2026-03-07-MOL": ("INCLUDE","B",None,["AUTH-IDENTITY-SATISFIABLE-BY-ATTACKER-CONTRACT"],["Base"],["token"]),
"INC-2026-03-06-SOL": ("EXCLUDE",None,"PATTERN_EXC_GRADE_D",[],["Ethereum"],["BTC staking","vault"]),
"INC-2026-03-02-INV": ("PROVISIONAL","C",None,["LIQUIDATION-ON-MANIPULABLE-VALUATION"],["Ethereum"],["CDP","lending"]),
"INC-2026-03-02-CUR": ("INCLUDE","A",None,["ORACLE-VAULT-SHARE-RATE-AS-SPOT-PRICE","ACC-DONATION-UNACCOUNTED-BALANCE","LIQUIDATION-ON-MANIPULABLE-VALUATION"],["Ethereum"],["lending","CDP"]),
"INC-2026-03-01-BIT": ("EXCLUDE",None,"EXC_INFRA_SERVER",[],["Bitcoin"],["payments"]),
"INC-2026-02-28-WIS": ("PROVISIONAL","C",None,["ACC-NAV-SHAREPRICE-MANIPULABLE"],["Ethereum","Arbitrum"],["lending"]),
"INC-2026-02-27-STA": ("PROVISIONAL","C",None,["AUTH-MISSING-ON-VALUE-MOVING-PATH"],["Solana"],["liquid staking"]),
"INC-2026-02-26-FOO": ("INCLUDE","A",None,["PROOF-VERIFICATION-BYPASSED"],["Base","Ethereum"],["privacy pool","gaming"]),
"INC-2026-02-26-PLO": ("INCLUDE","A",None,["ORACLE-STALE-OR-SILENT-FALLBACK"],["Ethereum"],["lending"]),
"INC-2026-02-25-HOL": ("EXCLUDE",None,"EXC_SUPPLY_CHAIN_FRONTEND",[],["multi"],["wallet"]),
"INC-2026-02-23-WLF": ("EXCLUDE",None,"EXC_PHISHING_SOCIAL",[],["Ethereum"],["stablecoin issuer"]),
"INC-2026-02-23-DGL": ("PROVISIONAL","C",None,["TOKEN-TRANSFER-OVERRIDE-BREAKS-CONSERVATION"],["Ethereum","Base"],["RWA token","bridge"]),
"INC-2026-02-22-BLE": ("INCLUDE","A",None,["ORACLE-SPOT-THIN-LIQUIDITY"],["Stellar"],["lending"]),
}
