# -*- coding: utf-8 -*-
"""Mechanism families, part C."""
def F(**kw): return kw
FAM_C = {

"ACC-CREDIT-NOT-RECEIVED": F(
 title="Reward or entitlement credited from an observed balance delta rather than value actually spent with the protocol",
 broken_invariant="Reward credit must be derived from economic value actually transferred to, or spent through, the protocol. A balance delta observed on a third-party venue is not proof of a purchase.",
 mechanism="A permissionless tracking function reads a token balance change on an external pair and treats it as a purchase, sizing a reward allocation from it. Projekt's trackPurchase read only balance deltas without verifying ETH spent, so the attacker flash-loaned ~14K WETH, pushed it through memecoin pairs and used skim() to fabricate purchase records, inflating allocations and draining ~301.7 ETH via massWithdraw.",
 mandatory_preconditions=["Permissionless function that records an entitlement","Entitlement sized from an observed balance/state delta rather than a transfer into the protocol","No binding between the recorded action and value received by the protocol","A funded reward reserve is claimable against the recorded entitlement"],
 optional_amplifiers=["Flash loans","skim()/sync() to fabricate deltas","Batch withdraw function"],
 applicable_protocol_archetypes=["reward distributor","points/airdrop system","farm","launchpad","loyalty/rebate system"],
 static_indicators=["trackPurchase/recordBuy/registerAction style external functions","balanceOf deltas used as the reward basis","no msg.value or transferFrom in the crediting path"],
 adapter_indicators=["adapter counts a reward pool balance as TVL","adapter references a distributor separate from the core protocol"],
 runtime_state_indicators=["reward reserve balance large relative to protocol revenue","entitlement mapping writable by arbitrary callers"],
 cross_contract_indicators=["crediting contract observes pools it does not control"],
 decisive_guards=["Credit amount taken from the post-transfer balance delta of the protocol's own accounting boundary","Purchases proven by a receipt the protocol itself minted during the swap","Per-address caps and eligibility consumption"],
 false_positive_killers=["Credit derived from transferFrom into the protocol (kills the pair)","Entitlements written only by a trusted settlement path"],
 local_defensive_property="On a fork, fabricate the observable precondition without transferring value to the protocol; the entitlement must not increase.",
 evidence_strength="MEDIUM", propagation_notes="SINGLE_EVENT_FAMILY in-window. Retained because the prerequisites are unusually observable and reward reserves are commonly funded well above the cost of fabricating a delta."),

"ACC-SPLIT-NONINVARIANT": F(
 title="Per-operation pricing or state contraction is not invariant to splitting or recombining the same total amount",
 broken_invariant="Executing an operation once for amount N and executing it k times for N/k must produce the same total economic result. Any per-operation averaging, contraction factor or rounding that breaks this yields free value to whoever splits.",
 mechanism="USM's ethFromDefund() priced a redemption at the arithmetic mean of current and estimated final FUM sell prices; combined with a per-redemption contraction (adjShrinkFactor) and integer rounding, 64 small defund() calls extracted more ETH than one large call. Lien Finance's exchangeEquivalentBonds omitted multiset integrity checks, so a bond set could be exchanged for one that was not economically equivalent, minting unbacked bonds.",
 mandatory_preconditions=["A public operation whose price/fee/state update is computed per call","The formula is non-linear in amount, or applies a per-call contraction, or rounds directionally","The operation can be repeated freely in one transaction","Value is realisable from the difference"],
 optional_amplifiers=["Flash loans to pre-position","Low gas cost per call","No minimum operation size"],
 applicable_protocol_archetypes=["stablecoin issuer","structured product","options","AMM with custom curve","bond/tranche protocol"],
 static_indicators=["average-of-two-prices formulas","shrink/contraction factors applied per call","no assertion that f(N) == sum(f(N/k))","exchange/split/merge functions without a value-conservation assert"],
 adapter_indicators=["adapter models a custom bonding curve or tranche system","protocol methodology mentions a bespoke pricing formula"],
 runtime_state_indicators=["contraction/shrink parameters non-neutral","no per-transaction operation-count limit"],
 cross_contract_indicators=["split and merge handled by different modules with different math"],
 decisive_guards=["Explicit split-invariance assertion in tests and on-chain bounds","Value-conservation assert across exchange/split/merge (sum of inputs == sum of outputs at one price)","Rounding always against the caller"],
 false_positive_killers=["Pricing is linear in amount","A conservation assert reverts on any imbalance (kills the pair)"],
 local_defensive_property="Property test: for random N and k, assert result(N) >= sum(result(N/k)) within one wei, on the deployed bytecode.",
 evidence_strength="MEDIUM", propagation_notes="Two independent protocols, both with bespoke pricing. Bespoke curve math, not forked code, is the prerequisite; look for protocols whose methodology describes a custom formula."),

"ACC-REWARD-INDEX-INIT-AND-ORDERING": F(
 title="Accrual index not initialised at join, or not updated before the balance change it prices",
 broken_invariant="A user's reward accrual must be computed against the index in force for the period they actually held the balance. The index must be initialised at join and updated before any balance change.",
 mechanism="Three shapes: dividends distributed before balance updates, so a small deposit sets the accrual basis and a large deposit is then priced on the old, small share (NovaBox: 427.5 WETH flash loan, ~145.82 ETH of phantom dividends, pool drained 65.11 -> 0.09 ETH); deposit/withdraw looped to mint inflated shares before rewards settle, redeemed after harvest (Goose Finance StrategyGooseEgg); an uninitialised variable in an accumulator so a 0.2 SUI stake generated 162 trillion points and drained ~150,000 SUI (Scallop's deprecated V2 rewards contract).",
 mandatory_preconditions=["Reward/points accrual keyed on an index or checkpoint","Index initialisation or update ordering is wrong relative to balance changes","Deposit and claim reachable in a short window","A funded reward pool is claimable"],
 optional_amplifiers=["Flash loans","Harvest triggerable by the caller","Deprecated rewards contract with leftover funds"],
 applicable_protocol_archetypes=["reward distributor","farm","staking pool","yield aggregator","lending with incentives"],
 static_indicators=["_distribute/_harvest called before _mint/_burn of shares","userIndex not set on first interaction","points formula reading an uninitialised struct field","claim path not calling updateIndex first"],
 adapter_indicators=["adapter lists reward/gauge contracts separately","adapter includes deprecated reward pools"],
 runtime_state_indicators=["reward pool balance large relative to legitimate emissions","user index entries at zero for active positions","deprecated reward contracts still funded"],
 cross_contract_indicators=["strategy harvest callable by anyone and observable by the share math"],
 decisive_guards=["Checkpoint-before-mutate ordering enforced by a modifier on every balance-changing path","User index initialised to the global index on first interaction","Same-block deposit-and-claim disallowed"],
 false_positive_killers=["Every balance-changing path calls the accrual update first (kills the pair)","Rewards vest over time rather than being claimable immediately"],
 local_defensive_property="On a fork, deposit-claim-withdraw in one transaction from a fresh address; realised reward must be zero.",
 evidence_strength="HIGH", propagation_notes="Two of three were on abandoned or deprecated reward contracts still holding funds, linking this family to UPGRADE-OLD-DEPLOYMENT-LIVE-AUTHORITY."),

"ACC-DUPLICATE-ID-ACCUMULATION": F(
 title="An array of IDs is accumulated without deduplication or consumption",
 broken_invariant="An entitlement attached to an identifier may be counted at most once per period. A caller-supplied ID list must be deduplicated, or each ID's claim state consumed before the next read.",
 mechanism="A batch function loops a caller-supplied ID array, accumulating an amount per entry, and only writes the consumed marker after the loop. Repeating the same ID multiplies the payout. ApeBond's migrateToVotingEscrow accepted duplicate pool IDs, inflating a lock from ~1.71 to ~29 quadrillion ABOND. LootBot AI's redeem() accepted 7 NFT IDs each repeated 155 times because nextRedeem was updated only after payout.",
 mandatory_preconditions=["Batch function takes a caller-supplied array of IDs","Per-ID amount accumulated inside the loop","Consumed/claimed state written after the loop, or not at all","A funded pool pays the accumulated amount"],
 optional_amplifiers=["Flash loans to trigger a fresh epoch","No array length cap"],
 applicable_protocol_archetypes=["reward distributor","NFT staking","vote-escrow migration","airdrop claim","farm"],
 static_indicators=["for-loops over calldata ID arrays with += accumulation","state write after the loop rather than inside it","no seen-set or sorted-strictly-increasing requirement"],
 adapter_indicators=["adapter enumerates pools/positions by ID","adapter references a migration or claim helper"],
 runtime_state_indicators=["claim pool funded","claimed-marker mappings sparsely populated relative to activity"],
 cross_contract_indicators=["migration helper trusted by an escrow/lock contract"],
 decisive_guards=["Mark each ID consumed inside the loop before accruing","Require strictly increasing IDs to make duplicates impossible","Deduplicate into a set before accumulation"],
 false_positive_killers=["Consumed marker written inside the loop (kills the pair)","IDs required strictly increasing"],
 local_defensive_property="On a fork, call the batch function with one ID repeated k times; payout must equal the single-ID payout.",
 evidence_strength="MEDIUM", propagation_notes="Cheap to screen: find every external function taking an array of IDs and check for in-loop consumption."),

"ACC-SIGN-OR-BOUND-CHECK-MISSING": F(
 title="A signed or unbounded parameter inverts or inflates a value transfer",
 broken_invariant="A quantity that must be non-negative and bounded must be checked at the boundary. Casts between signed and unsigned types must be range-checked.",
 mechanism="Drips Network cast uint128 to int128 in DaiDripsHub.give(), so a large positive value became negative and reversed the transfer direction, draining 24,882.99 DAI from DaiReserve. Aftermath Finance allowed negative 'builder code' fees, inflating synthetic collateral and draining ~$1.14M across 11 transactions. Dango's insurance fund accepted donations without verifying the amount was positive.",
 mandatory_preconditions=["A caller-influenced numeric parameter feeds a transfer, fee or collateral computation","No range/sign check, or an unchecked cast between signed and unsigned","The sign or magnitude change is realisable as value","Reachable by an unprivileged caller"],
 optional_amplifiers=["Solidity unchecked blocks","Custom fixed-point libraries","Move/Rust integer semantics differing from EVM"],
 applicable_protocol_archetypes=["derivatives/perpetuals","streaming payments","insurance fund","fee/rebate system","any protocol with configurable fees"],
 static_indicators=["int128(uint128(x)) / int256(uint256(x)) casts without SafeCast","fee parameters typed as signed integers","donate/deposit functions with no amount > 0 require","unchecked { } around arithmetic on user input"],
 adapter_indicators=["adapter reads a fee or funding parameter","protocol methodology mentions builder codes, rebates or negative fees"],
 runtime_state_indicators=["fee/rebate parameters currently negative or outside a sane range","insurance/reserve balances reachable by a public donate path"],
 cross_contract_indicators=["fee parameters settable per-integrator rather than globally"],
 decisive_guards=["SafeCast on every cross-sign cast","require(amount > 0) and explicit upper bounds on every caller-influenced quantity","Fee parameters clamped to [0, max] at the setter"],
 false_positive_killers=["SafeCast used throughout and fees clamped at the setter (kills the pair)","No signed arithmetic in the value path"],
 local_defensive_property="Fuzz every external numeric parameter across type boundaries and assert no entrypoint produces a transfer to the caller exceeding their entitlement.",
 evidence_strength="HIGH", propagation_notes="Appears across EVM, Move and a Cosmos-SDK chain in-window, so it is language-independent. Integrator-configurable fee parameters (builder codes, rebates) are the newest and least-audited surface."),

"ACC-MULTI-PATH-CREDIT-DRIFT": F(
 title="The same balance is reachable through multiple code paths that account for it differently",
 broken_invariant="Every path that can credit or debit a given balance must apply identical accounting. Where a protocol offers module sidecars, legacy plus current paths, or several entrypoints to one pool, cycling between them must be value-neutral.",
 mechanism="Ambient Finance's monolithic contract exposed HotProxy, WarmPath and ColdPath over shared surplus-collateral accounting; rapid cycling extracted ~83.72 ETH. Haedal's Sui vaults kept a deprecated deposit path alive after a 2025 upgrade: minting inflated LP shares through the old path and redeeming through the new one yielded ~$915K. Maya Protocol chained six edge cases across Trade Account, outbound handling and pool math to inflate accounting via a false subsidy, then extracted through add/remove liquidity.",
 mandatory_preconditions=["Two or more reachable code paths mutate the same balance or share supply","Their accounting differs (rounding, fee, subsidy, version, or ordering)","A caller can cycle between them in one transaction or one block","Value is realisable from the drift"],
 optional_amplifiers=["Proxy/sidecar architecture","Version migration in progress","Cross-module subsidy or rebate logic","Flash liquidity"],
 applicable_protocol_archetypes=["DEX/AMM (monolithic/singleton)","vault/share token after upgrade","cross-chain liquidity network","lending with multiple entry modules"],
 static_indicators=["several proxies/paths delegating into one storage layout","deprecated deposit/withdraw retained alongside new ones","subsidy or rebate logic spanning modules","different rounding directions in sibling functions"],
 adapter_indicators=["adapter references several proxy/path addresses for one protocol","adapter still lists a legacy path with the current one"],
 runtime_state_indicators=["both old and new entrypoints succeed in simulation","share supply reachable through more than one mint function","surplus/credit balances non-zero for arbitrary addresses"],
 cross_contract_indicators=["shared storage across proxies","module boundaries with no common invariant check"],
 decisive_guards=["One canonical accounting function all paths call","Global invariant assert (total shares vs total assets) at the end of every external call","Deprecated paths disabled atomically with the upgrade"],
 false_positive_killers=["All mint/burn routes through a single internal function with a closing invariant assert (kills the pair)","Only one live entrypoint per balance"],
 local_defensive_property="On a fork, enumerate all entrypoints touching a given balance and fuzz orderings; assert the global share/asset invariant holds after every sequence.",
 evidence_strength="HIGH", propagation_notes="This is the failure mode of singleton and modular architectures, which are increasing. It is invisible to per-function review and only appears under cross-path fuzzing."),

"ACC-HARDCODED-PEG-REDEMPTION": F(
 title="Redemption honours a hardcoded peg that the mint side validates but the burn side does not",
 broken_invariant="If minting checks that the market price is at peg, redemption must apply the symmetric check. Asymmetric validation lets anyone buy the asset below peg and redeem it at par against real collateral.",
 mechanism="Chi Protocol's ArbitrageV5.burn() redeemed USC for weETH/stETH/WETH at a hardcoded $1 while mint checked the peg; the attacker flash-bought heavily depegged USC on a thin Uniswap V2 pool and redeemed at par, nearly draining reserves.",
 mandatory_preconditions=["Redemption values the protocol asset at a fixed or hardcoded price","The mint path applies a peg/market check the burn path omits","The asset trades below that price on a reachable venue","Redeemable collateral is held"],
 optional_amplifiers=["Thin secondary market","Flash loans","Depeg already in progress"],
 applicable_protocol_archetypes=["stablecoin issuer","CDP","synthetic asset","RWA token"],
 static_indicators=["burn/redeem using a constant 1e18 price while mint reads an oracle","asymmetric require sets between mint and burn","arbitrage module with one-sided checks"],
 adapter_indicators=["adapter prices the protocol's stablecoin at a hardcoded $1","`misrepresentedTokens` or peg assumptions in methodology"],
 runtime_state_indicators=["market price of the asset materially below the redemption price","collateral reserve redeemable at par","no redemption cap or fee scaling with the depeg"],
 cross_contract_indicators=["arbitrage/stability module holds the reserve while the token contract holds the peg logic"],
 decisive_guards=["Symmetric peg validation on mint and burn","Redemption priced from the same oracle as minting","Redemption fee or cap scaling with observed depeg"],
 false_positive_killers=["Burn reads the same oracle as mint (kills the pair)","Redemption disabled below a price band"],
 local_defensive_property="On a fork, depeg the asset on its deepest venue and attempt redemption; the protocol must price the redemption at market or revert.",
 evidence_strength="MEDIUM", propagation_notes="SINGLE_EVENT_FAMILY. Directly checkable by diffing the require-sets of mint and burn in deployed source."),

"SETTLEMENT-EPOCH-BOUNDARY-CREDIT": F(
 title="Value credited using a per-epoch fixed figure that can be claimed across the boundary",
 broken_invariant="A quantity fixed for an epoch must not be claimable against a position established after that quantity was set, and entitlement must be prorated by time actually held.",
 mechanism="LOOPSDAO's LpdFi opened a hugely inflated interest-bearing position using a manipulated spot price and claimed interest right across the daily settlement boundary, forcing the protocol to burn its own Cake-LP and pay ~$690K. Fractal Protocol's USDF vault used a fixed daily-accrued tokenPrice (~1.27 USDC/USDF) that, combined with share rounding and re-entrant Balancer batchSwap callbacks, let deposit and withdraw be recursed inside one epoch.",
 mandatory_preconditions=["A rate/price/accrual is fixed for an epoch and read at claim time","A position can be created and claimed within, or straddling, one epoch","No proration by holding time","A funded pool honours the claim"],
 optional_amplifiers=["Flash loans","Predictable settlement timestamp","Re-entrant callbacks inside the epoch","Referral or multiplier logic"],
 applicable_protocol_archetypes=["epoch settlement","lending with daily accrual","yield vault with periodic pricing","structured product","perpetuals funding"],
 static_indicators=["lastSettlement/epochId timestamps with a fixed stored price","claim paths reading a stored price rather than a live one","no time-weighting in the entitlement formula"],
 adapter_indicators=["adapter reads a stored price-per-share updated on a schedule","methodology describes daily or periodic settlement"],
 runtime_state_indicators=["stored epoch price stale relative to live market","deposits spiking immediately before settlement","no minimum holding period"],
 cross_contract_indicators=["settlement keeper callable by anyone","epoch price set by an off-chain updater on a fixed cadence"],
 decisive_guards=["Time-weighted entitlement (prorate by seconds held within the epoch)","Minimum holding period or deposit lock across settlement","Deposits after the epoch price is fixed accrue from the next epoch"],
 false_positive_killers=["Entitlement time-weighted (kills the pair)","Deposits queued to the next epoch"],
 local_defensive_property="On a fork, deposit one second before settlement and claim one second after; realised value must be ~zero.",
 evidence_strength="MEDIUM", propagation_notes="Overlaps ORACLE-STALE-OR-SILENT-FALLBACK (a stored epoch price is a stale price) but the decisive guard is time-weighting, not a better feed, so it is kept separate."),

"ORACLE-VAULT-SHARE-RATE-AS-SPOT-PRICE": F(
 title="An ERC-4626 share rate (convertToAssets / pricePerShare) is used directly as a collateral price feed",
 broken_invariant="A vault share rate is an accounting quantity of another protocol, not a market price. Using it as a feed imports every way that vault's rate can be moved, including donation inflation and same-transaction redemption effects.",
 mechanism="Curve LlamaLend's CryptoFromPoolVaultWAgg oracle called sDOLA.convertToAssets() as a spot feed. The rate was atomically manipulable by large redemptions and re-deposits and by a DolaSavings.stake() donation, which lifted it 13.79% (1.189 -> 1.353) and hard-liquidated 27 borrowers holding ~$10.9M of debt. Edel Finance's lending market valued wGOOGLx by its wrapper exchange rate, which repeated deposit/borrow loops inflated ~78x, creating ~$403K of bad debt.",
 mandatory_preconditions=["A lending/CDP market prices collateral via a share rate or wrapper exchange rate","That rate is influenceable by an unprivileged actor (donation, redemption, loop) in a short window","No deviation bound or TWAP is applied to the rate","Live borrow capacity or liquidation eligibility depends on it"],
 optional_amplifiers=["Flash loans","Large share supply held outside collateralised positions","Soft-liquidation mechanics amplifying small rate moves","Wrapper with a thin underlying"],
 applicable_protocol_archetypes=["lending","CDP","risk curator","leveraged vault","basis trading"],
 static_indicators=["oracle contracts named *FromPoolVault*, *4626*, *WrapperRate*","price = vault.convertToAssets(1e18) with no bounds","pricePerShare()/getPricePerFullShare() in a price path"],
 adapter_indicators=["adapter lists ERC-4626 vault tokens as collateral","adapter values a wrapper by its own exchange rate","market list includes yield-bearing wrappers"],
 runtime_state_indicators=["collateral assets that are ERC-4626 shares or wrappers","the underlying vault's rate movable by donation (see ACC-DONATION family)","share supply outside collateral positions large enough to move the rate"],
 cross_contract_indicators=["the priced vault is a different protocol with its own risk surface","no rate-change cap between the two protocols"],
 decisive_guards=["Rate capped by a growth-rate adapter (max APR) with a hard deviation bound","Rate smoothed over time and floored/ceilinged","Underlying vault verified non-donation-inflatable before listing","Independent market price cross-check for the wrapper"],
 false_positive_killers=["Growth-capped rate adapter in the deployed oracle (kills the pair)","Wrapper's own rate is monotonic and rate-limited","Collateral priced by an independent market feed instead"],
 local_defensive_property="On a fork, donate to and cycle the underlying vault; assert the lending market's reported collateral price moves no more than the configured cap.",
 evidence_strength="HIGH", propagation_notes="Yield-bearing collateral is now standard, so this shape is spreading fast. It is the intersection of ACC-DONATION-UNACCOUNTED-BALANCE (in the priced vault) and the lending market that trusts it; screen the pair, not either side alone."),

"SIG-REPLAY-CROSS-POSITION": F(
 title="A signature is valid across positions, accounts or contexts because the digest omits the identifier",
 broken_invariant="A signed authorisation must bind to exactly one position, account, chain, contract and nonce, and must be consumable once.",
 mechanism="Atomic Green's manager signature was replayable across 21 different Uniswap V3 LP positions because the position ID was not part of the signed digest; combined with flash-loan price manipulation it triggered unauthorised full LP burns for ~29,984 USDC.",
 mandatory_preconditions=["An off-chain signature authorises an on-chain action","The digest omits the position/account/context identifier or a nonce","Multiple instances exist that the same signature satisfies","Those instances hold value"],
 optional_amplifiers=["Many positions under one manager","Signature published on-chain by first use","Flash-loan price manipulation to make the burn profitable"],
 applicable_protocol_archetypes=["liquidity manager","leveraged trading","vault manager","NFT position manager","intents/RFQ"],
 static_indicators=["EIP-712 structs lacking positionId/tokenId/nonce/deadline","hash built from action type and amount only","no usedSignature/nonce mapping"],
 adapter_indicators=["adapter enumerates many per-user positions under one manager","manager-operated LP strategies"],
 runtime_state_indicators=["many live positions under one manager address","no nonce mapping populated","manager signature reuse visible in historical calldata"],
 cross_contract_indicators=["one manager signs for positions across several pools or chains"],
 decisive_guards=["Position/token ID, chainId, verifying contract, nonce and deadline all in the signed struct","Nonce consumed before external calls","Signature bound to a single position by construction"],
 false_positive_killers=["Digest includes the position ID and a consumed nonce (kills the pair)","Actions authorised on-chain per position rather than by signature"],
 local_defensive_property="On a fork, capture a signature used on position A and replay it against position B; it must revert.",
 evidence_strength="MEDIUM", propagation_notes="SINGLE_EVENT_FAMILY. Blast radius scales with position count under one signer, so exposure can be far larger than the observed loss."),

"SIG-DIGEST-AMBIGUOUS-OR-UNBOUND": F(
 title="Critical action fields are outside the signed digest, or the digest encoding is ambiguous",
 broken_invariant="Every field that changes the economic effect of an authorised action must be inside the signed digest, and the encoding must be injective so no two distinct messages hash equal.",
 mechanism="Giddy's GiddyVaultV3 validated only part of the SwapInfo struct under EIP-712, leaving aggregator, fromToken, toToken and amount unsigned; the attacker replayed a valid signature with substituted fields (strategy LP tokens as fromToken, an attacker aggregator, a malicious toToken, max amount) for ~$1.3M. Butter Bridge's OmniServiceProxy hashed retry messages with abi.encodePacked over dynamic-bytes fields, so a colliding message forged authentication and minted ~10^15 MAPO.",
 mandatory_preconditions=["A signed message authorises a parameterised action","At least one economically decisive field is outside the digest, or encoding is ambiguous (packed dynamic fields)","The action moves value or mints","Reachable by presenting a valid-looking signature"],
 optional_amplifiers=["Aggregator/router indirection","Retry or replay paths","Historic signatures available on-chain"],
 applicable_protocol_archetypes=["vault/share token","yield aggregator","bridge","cross-chain messaging","intents/RFQ","meta-transaction relayer"],
 static_indicators=["EIP-712 typehash covering fewer fields than the function parameters","abi.encodePacked over two or more dynamic types in a hash","retry/replay entrypoints reusing an old digest"],
 adapter_indicators=["adapter references an aggregator or router the protocol calls with signed instructions"],
 runtime_state_indicators=["historic signed calls whose parameters exceed the signed field set","retry queues with unconsumed messages"],
 cross_contract_indicators=["signature verified in one contract, action executed in another with extra parameters"],
 decisive_guards=["Typehash covering every parameter that affects the outcome","abi.encode (not encodePacked) for dynamic fields, or length-prefixed encoding","Nonce and deadline in the digest, consumed once"],
 false_positive_killers=["Typehash field set equals the function parameter set (kills the pair)","abi.encode used throughout"],
 local_defensive_property="On a fork, take a valid signature and vary each unsigned parameter; every variation must revert.",
 evidence_strength="HIGH", propagation_notes="Cheap and decisive to check by diffing the EIP-712 typehash against the executing function's parameter list in verified source."),

"SIG-VERIFIER-DEFEATABLE": F(
 title="Signature verification returns true for input that carries no authorisation",
 broken_invariant="A verification routine must reject malformed, empty or zero-recovered signatures, and must never treat address(0) as a match.",
 mechanism="MoneyMon's verify() checked only recoverSigner(...) == admin without handling ecrecover returning address(0); with admin set to the zero address, an invalid signature (r=0, s=0, v=27) passed and drained the contract. Lixir Finance's lv_* wrappers had broken EIP-2612 permit verification, so one dummy signature granted the attacker approval over dozens of holders' tokens.",
 mandatory_preconditions=["A signature check gates a value-moving action","The check can return true without a valid signer (ecrecover zero, unchecked return, malformed accepted)","The gated action moves value or grants approval","Reachable by an unprivileged caller"],
 optional_amplifiers=["Admin/signer address set to zero","Wrapper tokens holding many users' assets","Permit-based approval flows"],
 applicable_protocol_archetypes=["reward distributor","wrapper/vault token","NFT staking","payments","any permit-enabled token"],
 static_indicators=["ecrecover used without a require(signer != address(0))","permit implementations diverging from the EIP-2612 reference","verification result compared to a mutable address that may be zero"],
 adapter_indicators=["adapter lists wrapper tokens with custom permit implementations"],
 runtime_state_indicators=["admin/signer variable reading address(0)","wrapper tokens with many holders and live balances"],
 cross_contract_indicators=["one wrapper's permit governs assets held in another contract"],
 decisive_guards=["require(recovered != address(0) && recovered == expected)","Use of ECDSA.recover (OZ) which reverts on invalid signatures","Signer address immutable or non-zero-enforced at the setter"],
 false_positive_killers=["OZ ECDSA library in the deployed bytecode (kills the ecrecover-zero shape)","Signer address immutable and non-zero"],
 local_defensive_property="On a fork, submit r=0,s=0,v=27 and an empty signature to every signature-gated entrypoint; all must revert.",
 evidence_strength="HIGH", propagation_notes="Trivially screenable from verified source; the zero-address branch is the single highest-signal grep in the whole library."),

"AUTH-PUBLIC-CLAIM-NO-ELIGIBILITY": F(
 title="A public claim path pays from a reserve with no eligibility binding or consumption",
 broken_invariant="A claim must be bound to a caller-specific entitlement that is checked and consumed exactly once.",
 mechanism="MOKE's MokeToken.releaseContract() exposed claim() with no eligibility check on the caller; repeated calls drained ~166 million MOKE from the internal reserve, converted via flash loans, Venus leverage, LP removal and dividend distribution into ~1,546 BNB (~$907.7K).",
 mandatory_preconditions=["Public claim/release function pays from a protocol-held reserve","No mapping binding the caller to an entitlement, or the entitlement is not consumed","The reserve is funded","Reachable without privilege"],
 optional_amplifiers=["Repeatable in a loop","Dividend/LP mechanics to convert the claimed token","Leverage venue for the claimed asset"],
 applicable_protocol_archetypes=["token with reserve/release schedule","reward distributor","airdrop claim","launchpad","vesting contract"],
 static_indicators=["claim()/release() with no msg.sender lookup","no claimed[msg.sender] mapping, or set after transfer","amount derived from contract balance rather than entitlement"],
 adapter_indicators=["adapter counts a release/reserve contract's balance as TVL"],
 runtime_state_indicators=["release/reserve contract holding a large balance","claim entitlement mapping empty while the reserve is funded"],
 cross_contract_indicators=["reserve contract funded by the token contract on a schedule"],
 decisive_guards=["Caller eligibility mapping checked and consumed once before transfer","Merkle-proof-gated claims with nullifiers","Per-address and global claim caps"],
 false_positive_killers=["Claim requires a proof or a populated entitlement mapping (kills the pair)","Reserve holds zero balance"],
 local_defensive_property="On a fork, call the claim path from a fresh address with no prior interaction; it must transfer nothing.",
 evidence_strength="MEDIUM", propagation_notes="SINGLE_EVENT_FAMILY in-window but the canonical shape: exposure equals the reserve balance and is readable in one call."),

"AUTH-ZERO-ADDRESS-ACCEPTED": F(
 title="address(0) is accepted as valid authority, so renounced ownership can be reclaimed",
 broken_invariant="Renouncing ownership must permanently remove the capability. A check of the form caller == owner must never pass when owner is the zero address, and no default-zero role may be satisfiable.",
 mechanism="ONTR's onlyOwner check accepted owner == address(0), so a renounced token could be re-owned; combined with hidden balance-grant logic that fabricated balances without totalSupply or mint events, the attacker dumped into the ONTR/WETH pool. The same primitive appears in MoneyMon, where admin was the zero address and ecrecover's zero return matched it.",
 mandatory_preconditions=["An authority check compares against a variable that may be address(0)","That variable is currently zero, or reachable to zero via renounce","The gated function moves value or grants authority","Reachable by an unprivileged caller"],
 optional_amplifiers=["Publicly advertised 'ownership renounced' status reducing scrutiny","Hidden balance-granting logic","Recovered signer defaulting to zero"],
 applicable_protocol_archetypes=["token","any contract advertising renounced ownership","reward distributor"],
 static_indicators=["require(msg.sender == owner) with no owner != address(0) assertion","custom Ownable variants","role mappings whose default value is satisfiable"],
 adapter_indicators=["adapter includes tokens marketed as ownership-renounced"],
 runtime_state_indicators=["owner()/admin reading address(0) on a contract that still holds value or authority","renounce transaction in history with privileged functions still present"],
 cross_contract_indicators=["a renounced contract still holds a role in a funded system"],
 decisive_guards=["Assert owner != address(0) inside the modifier","Renounce implemented as a permanent capability removal (functions self-disable), not an address write","OZ Ownable2Step with zero-address rejection"],
 false_positive_killers=["Modifier asserts non-zero owner (kills the pair)","Renounce removes the functions' effect, not just the address"],
 local_defensive_property="Read owner/admin on every live contract; where zero, simulate every privileged selector from an arbitrary address and require a revert.",
 evidence_strength="MEDIUM", propagation_notes="Read-only detectable at scale: owner() == address(0) plus a non-zero balance is a two-call screen across an entire address set."),

"AUTH-IDENTITY-SATISFIABLE-BY-ATTACKER-CONTRACT": F(
 title="An authorisation check resolves identity through a caller-supplied address or an imitable property",
 broken_invariant="Authorisation must bind to an immutable identity the caller cannot supply, deploy or imitate. A check answered by code the caller controls is not a check.",
 mechanism="Mure's MureDistribution passed an attacker-supplied contract as the signature 'signer source', so SignatureChecker (ERC-1271 path) returned true and pre-approved QUEST tokens were drained via transferFrom. Ink Finance's Workspace Treasury accepted a deployed contract matching a whitelisted claimer identity, passing claim() authentication for ~$140K. Molt EVM's onlySpawnerToken modifier was satisfied by a deployed contract, allowing mintFromSpawner().",
 mandatory_preconditions=["An authorisation path resolves identity via a caller-supplied address, an interface probe, or a property an attacker can reproduce","No immutable allowlist or registry membership check","The gated action moves value or mints","Reachable permissionlessly"],
 optional_amplifiers=["ERC-1271 support","CREATE2 address grinding","Interface-detection (ERC-165) used as authorisation","Factory-registered identities"],
 applicable_protocol_archetypes=["reward distributor","DAO treasury","token with spawner/minter relationships","payments","any ERC-1271 integration"],
 static_indicators=["SignatureChecker / isValidSignature with a caller-supplied signer","modifiers checking an interface or a name rather than a registry","authorisation via tx-supplied address parameters"],
 adapter_indicators=["adapter references factory-spawned contracts trusted by a parent"],
 runtime_state_indicators=["whitelists keyed on something other than an immutable address","registries writable without timelock","pre-existing approvals to the distributor"],
 cross_contract_indicators=["parent token trusts any contract satisfying a shape rather than a registered address"],
 decisive_guards=["Immutable allowlist / registry membership required, checked by address","Signer address fixed at deployment or set only through a timelock","ERC-1271 accepted only from a registered set"],
 false_positive_killers=["Authorisation checked against an immutable address set (kills the pair)","No caller-supplied address enters the authorisation decision"],
 local_defensive_property="On a fork, deploy a contract that answers every probe affirmatively and attempt each gated action; all must revert.",
 evidence_strength="HIGH", propagation_notes="Growing with ERC-1271 and smart-account adoption: any integration that accepts a caller-nominated signer inherits this shape."),

"SECRET-EMBEDDED-IN-PUBLIC-CODE-AS-AUTH": F(
 title="A signing key or constant secret embedded in deployed code is used as authorisation",
 broken_invariant="Deployed bytecode is public. Nothing inside it can be a secret, so no authorisation may depend on knowledge of a value present in the contract.",
 mechanism="Swan Treasury's ZhaiquanBuy contract hardcoded the off-chain _signer key, so anyone could forge valid signatures and buy ~687,000 STY at roughly a 100x discount for ~$625K profit. The third-party SquidRouterModule authenticated arbitrary calldata execution by comparing against a publicly visible constant string, draining ~$3.2M from 86 Gnosis Safes. SQ Protocol's verified Staking contract contained a hardcoded owner backdoor, taken over via an EIP-7702 type-4 authorizationList transaction for ~$346K.",
 mandatory_preconditions=["Authorisation depends on a value present in the deployed bytecode or verified source","That value gates a value-moving action","The contract holds value, or holds approvals/module rights over value","Reachable by anyone who reads the code"],
 optional_amplifiers=["Contract name resembling a reputable protocol","Installed as a Safe module or 7702 delegate","Verified source making the constant trivially findable"],
 applicable_protocol_archetypes=["token sale","staking pool","smart account module","asset management","any contract with an off-chain signer"],
 static_indicators=["private/internal constants named signer, secret, password, key","address constants used as signature recovery targets","string constants compared for authentication","hardcoded owner addresses alongside a public takeover path"],
 adapter_indicators=["adapter references a module or helper not published by the named protocol","name collision between an adapter address and a well-known protocol"],
 runtime_state_indicators=["module enabled on user Safes","7702 delegation designators pointing at the code","contract holding approvals or custody"],
 cross_contract_indicators=["third-party module trusted by user accounts but unaffiliated with the protocol it is named after"],
 decisive_guards=["No authorisation derived from in-code constants; signer keys held off-chain and only their address stored","Authentication by signature over a fresh nonce, not by knowledge of a constant","Module installation gated by a reviewed registry"],
 false_positive_killers=["Only public keys/addresses appear in code, never private material or shared secrets (kills the pair)","No module rights or approvals held"],
 local_defensive_property="Extract every constant from deployed bytecode and test whether presenting it authorises anything.",
 evidence_strength="HIGH", propagation_notes="Explicitly an on-chain design failure rather than a key leak: the secrecy assumption is embedded in the deployment. Name-squatting third-party modules are the most dangerous variant because users grant them standing authority."),

"CALLBACK-STATE-LOCK-INCOMPLETE": F(
 title="The state lock does not cover the callback window, or state is written after the external call",
 broken_invariant="No externally reachable state may be read as authoritative while an external call from the same flow is outstanding. Effects must be written before interactions, and the lock must span every re-entrant path including sibling functions.",
 mechanism="Joe Agent's _removeLiquidityViaContract sent BNB by low-level call before updating lpInfo[user].lpAmount, permitting ~25 re-entrant loops for 62.5 BNB and ~1.196M JOE. Set Protocol / Index Coop's ExchangeIssuance lacked sufficient state locking, so a malicious manager pre-issue hook inflated positionMultiplier and the contract transferred assets on falsified data. Fractal Protocol's USDF vault was recursed through Balancer V2 batchSwap callbacks into deposit and withdraw with no invariant check across the re-entrant flow.",
 mandatory_preconditions=["An external call (transfer, hook, callback) occurs before the state it depends on is finalised","A re-entrant path can read or mutate that state","The re-entered path moves value","Reachable by an unprivileged caller, possibly via a third-party callback"],
 optional_amplifiers=["Flash loans / batchSwap callbacks","Manager or module hooks","ERC-777/ERC-1363 callback tokens","Cross-function re-entrancy where the guard covers only one function"],
 applicable_protocol_archetypes=["vault/share token","farm","liquidity manager","indexes","structured product","lending"],
 static_indicators=["low-level call/transfer before state writes","nonReentrant applied to some but not all mutating functions","hooks invoked mid-computation","no invariant assert at function exit"],
 adapter_indicators=["adapter references hook/module contracts","protocol integrates external callback-bearing venues"],
 runtime_state_indicators=["hook/module addresses settable by a manager","integrations with callback-capable venues (Balancer vault, flash providers)"],
 cross_contract_indicators=["third-party callback re-enters a sibling function outside the guard"],
 decisive_guards=["Checks-Effects-Interactions applied throughout","A single global re-entrancy lock covering every mutating entrypoint, including siblings","Closing invariant assert (shares vs assets) at function exit","Hooks restricted to a reviewed allowlist"],
 false_positive_killers=["Global lock across all mutating functions plus CEI (kills the pair)","No external calls before state finalisation"],
 local_defensive_property="On a fork, attempt re-entry into every mutating entrypoint from every reachable callback; each must revert or leave the global invariant intact.",
 evidence_strength="HIGH", propagation_notes="Cross-function and cross-protocol re-entrancy through third-party callbacks (Balancer batchSwap, flash callbacks) is the live shape; single-function guards do not close it."),

"APPROVALS-TO-UPGRADEABLE-SPENDER": F(
 title="Live user approvals point at a contract whose implementation or authority can change",
 broken_invariant="The set of code that may spend a user's allowance must be fixed at the time the allowance is granted. If the spender is upgradeable, the user has approved future, unknown code.",
 mechanism="BarnBridge's attacker used DAO control to upgrade a proxy to a malicious implementation and then drained ~$776K through approvals ~50 addresses had already granted. Aurellion's re-initialisable diamond let the attacker add a facet with pullERC20/sweep and drain wallets that had approved the proxy. In both cases the approvals, not the TVL, were the value at risk.",
 mandatory_preconditions=["Users hold live allowances to an upgradeable contract (proxy, diamond, beacon, or module)","The upgrade path is reachable by governance, an EOA, or an initializer","Approving accounts still hold balances","No timelock or veto between upgrade and use"],
 optional_amplifiers=["Unlimited approvals","Long-lived integrations","Diamond facets addable individually","Beacon controlling many children"],
 applicable_protocol_archetypes=["governance-controlled proxy","router/aggregator","smart account module","diamond","any upgradeable spender"],
 static_indicators=["proxy/diamond/beacon with an upgrade path plus a token-pulling role","modules installable into user accounts"],
 adapter_indicators=["adapter references router/spender addresses users approve directly"],
 runtime_state_indicators=["aggregate live allowance value to the spender","proxy admin is an EOA or a non-timelocked governance executor","recent implementation changes"],
 cross_contract_indicators=["governance executor holds PROXY_ADMIN over an approved spender","beacon upgrade affects every child spender at once"],
 decisive_guards=["Timelock plus guardian veto on every upgrade path to an approved spender","Non-upgradeable spender contracts (approvals only to immutable code)","Per-flow allowances (Permit2 style) instead of standing approvals"],
 false_positive_killers=["Spender is immutable (kills the pair)","Aggregate live allowance is negligible (kills exposure)"],
 local_defensive_property="Enumerate live allowances to every upgradeable spender and treat their sum as value at risk in the upgrade path's threat model.",
 evidence_strength="MEDIUM", propagation_notes="An exposure multiplier rather than a standalone defect: it converts any governance or initializer weakness into direct user loss, and it is why TVL alone understates value at risk."),

"TOKEN-TRANSFER-OVERRIDE-BREAKS-CONSERVATION": F(
 title="A custom transfer override double-transfers, mis-deducts, or performs value-moving side effects",
 broken_invariant="A token transfer must conserve total supply plus balances: exactly `amount` leaves the sender and at most `amount` arrives, and the transfer must not move third-party or protocol-held value as a side effect.",
 mechanism="DIP's _transfer omitted a return statement on the PancakeSwap-routed branch, causing double transfers exploited with skim() and sync() for ~$111K. AIDC's _sellTransfer/burn accumulated burn fees without deducting them from the sender's balance, draining ~$121K WBNB. ATM's transferFrom automatically swapped ~20% of the transferred amount to BSC-USD, and repeatedly triggering it drained ~$243.5K. DGLD's legacy transferFrom edge case allowed unbacked wrapped supply on Base.",
 mandatory_preconditions=["Token overrides _transfer/transferFrom/_update with non-standard logic","A branch fails to conserve value (missing return, missing deduction, or a side-effect swap/mint)","The branch is reachable by an unprivileged caller","A pool or protocol holds value exposed to the branch"],
 optional_amplifiers=["Router-specific branches","skim()/sync() to realise the imbalance","Flash loans"],
 applicable_protocol_archetypes=["token with custom transfer logic","RWA/wrapped token","bridged token"],
 static_indicators=["multiple branches in _transfer with differing accounting","missing return in a branch","swap/mint invoked inside a transfer","fee accumulated without a matching debit"],
 adapter_indicators=["adapter values a token whose contract has custom transfer logic","misrepresentedTokens flag set"],
 runtime_state_indicators=["totalSupply not reconciling with the sum of tracked balances","pool balance drifting from reserves","wrapped supply exceeding locked backing"],
 cross_contract_indicators=["the same token deployed on several chains with divergent transfer logic"],
 decisive_guards=["Property test asserting conservation across every transfer branch","Fees taken only by reducing the credited amount","No external calls inside transfer"],
 false_positive_killers=["Standard OZ ERC-20 with no override (kills the pair)","Conservation asserted by an invariant test on deployed bytecode"],
 local_defensive_property="Property test on deployed bytecode: for every branch, sum(balances) + burned is invariant across a transfer, and no third-party balance changes.",
 evidence_strength="HIGH", propagation_notes="Sibling of the deferred-burn family: same archetype, different broken step (conservation inside the transfer rather than out-of-band mutation of the pair)."),

"TOKEN-TRANSFER-INTENT-HEURISTIC-FORGEABLE": F(
 title="Buy/sell/liquidity classification is inferred from a forgeable heuristic",
 broken_invariant="If a token applies different rules to buys, sells and liquidity operations, the classification must be derived from evidence the caller cannot fabricate.",
 mechanism="DTXT classified transfers by inspecting the pair's balances, so sending a small amount of USDT directly to the pair made large sells look like liquidity additions, bypassing sell fees and draining ~$35K. Movie Token (MT) whitelisted the router and pair to make deflationary mode work, and the attacker swapped and removed liquidity through the router to acquire MT outside the restriction, then used a referral rule allowing the first 0.2 MT to bypass buyer checks.",
 mandatory_preconditions=["Token applies different fee/restriction logic by inferred transfer intent","Classification derived from balances, addresses or amounts a caller can influence","Bypassing the classification yields value","Reachable permissionlessly"],
 optional_amplifiers=["Router and pair whitelists","Referral exemptions","Multiple pairs across routers"],
 applicable_protocol_archetypes=["token with custom transfer logic","launchpad token","farm token"],
 static_indicators=["from == pair / to == pair used as buy/sell detection","balance comparisons deciding fee branches","hardcoded router/pair exemptions","first-N-token referral exemptions"],
 adapter_indicators=["adapter values a fee-on-transfer token via pair reserves"],
 runtime_state_indicators=["exemption mappings populated with routers/pairs","multiple pairs for the token across routers"],
 cross_contract_indicators=["exemptions granted to contracts that can be called by anyone"],
 decisive_guards=["Classification from an explicit, protocol-minted receipt or an allowlisted entry function, not inference","No address-based exemptions for callable contracts","Same rules on every path"],
 false_positive_killers=["No per-intent branching (kills the pair)","Entry restricted to a protocol-controlled router that records intent explicitly"],
 local_defensive_property="On a fork, attempt each restricted operation through every alternative path (direct pair, router, add/remove liquidity) and assert the same fee/restriction applies.",
 evidence_strength="MEDIUM", propagation_notes="Always co-occurs with the deferred-burn family in this corpus; the heuristic bypass is what makes the burn reachable."),

"TOKEN-PACKED-OWNERSHIP-UNDERFLOW": F(
 title="Packed ownership or alias encoding with unchecked arithmetic",
 broken_invariant="An identifier packed alongside data must be range-checked, and arithmetic over packed fields must not underflow into an adjacent field.",
 mechanism="The shared DN404/BT404 codebase packed ownership with token-ID aliases; a malicious high-bit token ID combined with an unchecked integer underflow let the attacker mint near-infinite fpTokens/$BMP for dust WETH, drain pools and extract high-value NFTs (Flooring Protocol V2 / BitmapPunks). Asterix Labs, a Flooring fork, was hit the following day through the same codebase.",
 mandatory_preconditions=["Token packs ownership/alias/ID data into shared storage words","Arithmetic over packed fields is unchecked or the ID range is unvalidated","Mint or transfer quantity derives from the packed value","Live liquidity or NFT custody is exposed"],
 optional_amplifiers=["Hybrid ERC-20/ERC-721 (DN404/ERC-404 family)","Shared upstream codebase across forks","NFT custody alongside fungible liquidity"],
 applicable_protocol_archetypes=["NFT liquidity protocol","hybrid ERC-20/721 token","NFT fractionalisation"],
 static_indicators=["DN404/BT404/ERC-404 lineage","bit-packing helpers with unchecked blocks","token-ID alias arithmetic","no upper bound on token IDs"],
 adapter_indicators=["adapter values NFT liquidity vaults","adapter's protocol forked from a hybrid-token codebase"],
 runtime_state_indicators=["hybrid token contracts holding both NFT custody and AMM liquidity","fork lineage matching a known-vulnerable upstream"],
 cross_contract_indicators=["several deployments sharing one upstream library version"],
 decisive_guards=["Checked arithmetic on all packed-field operations","Explicit token-ID range validation","Upgrade to the patched upstream, verified in deployed bytecode"],
 false_positive_killers=["Deployed bytecode matches the patched upstream (kills the pair)","No packed ownership encoding"],
 local_defensive_property="Differentially test the deployed bytecode against the patched upstream on boundary token IDs.",
 evidence_strength="HIGH", propagation_notes="A genuine fork-clone lineage: Flooring and Asterix are one root cause across two deployments, one day apart, and count once toward unique root causes. Every unpatched DN404/BT404 deployment shares it."),

"HOOK-ZERO-VALUE-TRANSFER-TRIGGERS-ACCRUAL": F(
 title="A zero-value or dust transfer triggers a privileged accrual, mint or burn hook",
 broken_invariant="A transfer of zero (or dust) must be economically inert. Hooks that accrue, mint, harvest or burn must not be reachable by an operation that moves no value and bypasses authorisation.",
 mechanism="Little Boy Plus' LBPHashrate._update() was triggered by a zero-value transferFrom, bypassing OpenZeppelin's allowance path, calling _harvest and minting LBP straight to the PancakeSwap pair, inflating the pair's balance without a reserve update and enabling a ~$367K drain. Royal.io's Royal1155LD used 100 zero-value ERC-1155 transfers to manipulate beforeLdaTransfer, inflating pro-rata royalty balances for ~$263K.",
 mandatory_preconditions=["A transfer hook (_update, _beforeTokenTransfer, beforeLdaTransfer) performs accrual, mint, harvest or burn","Zero-value or dust transfers are not rejected before the hook","The hook's effect is value-bearing","Reachable permissionlessly, including from an unrelated account"],
 optional_amplifiers=["ERC-1155 batch transfers","Allowance checks skipped for zero amounts","Flash loans","Hook minting directly to an AMM pair"],
 applicable_protocol_archetypes=["reward distributor","farm","NFT royalties","token with accrual hooks","staking"],
 static_indicators=["accrual/mint/harvest logic inside a transfer hook","no require(amount > 0) before the hook","ERC-1155 hooks looping over ids with zero amounts"],
 adapter_indicators=["adapter references a royalty or accrual contract","reward accrual tied to token transfers"],
 runtime_state_indicators=["hook-bearing tokens with a funded reward or royalty pool","historical zero-value Transfer events in unusual volume"],
 cross_contract_indicators=["the hook mints into a pool it does not control"],
 decisive_guards=["require(amount > 0) before any hook side effect","Accrual moved out of transfer hooks into explicit, authorised functions","Hooks made idempotent and caller-authorised"],
 false_positive_killers=["Zero-amount transfers revert or short-circuit before the hook (kills the pair)","Hooks are pure bookkeeping with no mint/transfer"],
 local_defensive_property="On a fork, issue zero-value transfers in a loop against every hook-bearing token and assert no state with economic value changes.",
 evidence_strength="HIGH", propagation_notes="A general primitive rather than a chain-specific one, and unusually cheap for an attacker: the trigger costs only gas."),

"STORAGE-LAYOUT-COLLISION-PHANTOM-CREDIT": F(
 title="A storage slot collision turns a control sentinel into spendable credit",
 broken_invariant="Distinct logical variables must occupy distinct storage slots. A library that writes a fixed slot must not overlap application storage, and no control value may be readable as a balance.",
 mechanism="ATOHook's rewards mapping collided with Solady's fixed ReentrancyGuard slot; the nonReentrant modifier in getReward() wrote a sentinel value that was then read as a reward balance for the colliding address, letting the attacker claim a fixed amount 200 times for ~14.41 ETH.",
 mandatory_preconditions=["A library or pattern writes a hardcoded storage slot (transient or persistent)","Application state maps into the same slot space","The colliding value is interpreted as an amount or authorisation","The contract holds claimable value"],
 optional_amplifiers=["Solady/assembly-optimised libraries with fixed slots","Diamond storage patterns","Upgrades that reorder storage","Repeatable claim path"],
 applicable_protocol_archetypes=["reward distributor","AMM hook","diamond/upgradeable contract","any contract using fixed-slot libraries"],
 static_indicators=["Solady ReentrancyGuard or similar fixed-slot libraries alongside mappings at low slots","assembly sstore/tstore to constant slots","diamond storage without namespaced structs"],
 adapter_indicators=["adapter references hook or reward contracts built on assembly-optimised libraries"],
 runtime_state_indicators=["reward/credit entries for addresses with no interaction history","storage reads returning sentinel-like constants (1, 2, type(uint).max) as balances"],
 cross_contract_indicators=["upgrade history showing storage layout changes"],
 decisive_guards=["ERC-7201 namespaced storage","Storage-layout diffing in CI across upgrades and libraries","Sentinel values chosen outside any plausible amount range"],
 false_positive_killers=["Namespaced storage throughout (kills the pair)","No fixed-slot libraries in the deployed bytecode"],
 local_defensive_property="Dump the deployed storage layout and assert no application mapping's slot space intersects any library's fixed slot.",
 evidence_strength="MEDIUM", propagation_notes="SINGLE_EVENT_FAMILY, but rising: gas-optimised fixed-slot libraries and hook architectures are both spreading, and the collision is invisible in source review without a layout dump."),

"METATX-SENDER-IDENTITY-CONFUSION": F(
 title="Meta-transaction sender resolution disagrees across a trust boundary",
 broken_invariant="_msgSender() must resolve to the same principal everywhere authorisation is evaluated, and a contract must never be able to forward a call that makes itself the trusted forwarder for its own request.",
 mechanism="DBXen was drained ~$150K through an ERC-2771 sender identity inconsistency: the appended sender bytes were trusted in a context where the caller could control them. ShapeShift's FOX Colony on Arbitrum lost ~$132.7K via a meta-transaction self-call flaw combined with DSAuth authorisation, where a self-call let the contract authorise itself.",
 mandatory_preconditions=["Contract supports meta-transactions (ERC-2771 or custom) or DSAuth-style self-authorisation","The forwarder set is permissive, or self-calls are treated as authorised","Authorisation is evaluated using the resolved sender","Value or authority is reachable"],
 optional_amplifiers=["Multiple forwarders","Self-call helper functions","Legacy DSAuth patterns","Batch/multicall entrypoints appending sender bytes"],
 applicable_protocol_archetypes=["DAO treasury/governance","token with gasless transfers","farm","any ERC-2771 integration"],
 static_indicators=["_msgSender() overrides with trustedForwarder checks","address(this) accepted as an authorised caller","multicall combined with ERC-2771 (the classic self-forward)","DSAuth with a permissive authority"],
 adapter_indicators=["adapter references governance/colony contracts with meta-transaction support"],
 runtime_state_indicators=["trustedForwarder set to a permissive or self address","authority contract granting broad rights"],
 cross_contract_indicators=["forwarder trusted by several contracts with different authorisation models"],
 decisive_guards=["Single immutable trusted forwarder; self-address never trusted","Multicall disabled on ERC-2771 contracts, or sender bytes stripped","Authorisation on the true msg.sender for privileged actions"],
 false_positive_killers=["No meta-transaction support (kills the pair)","Forwarder immutable and address(this) explicitly rejected"],
 local_defensive_property="On a fork, craft a self-forwarded call appending an arbitrary sender and assert every privileged action reverts.",
 evidence_strength="MEDIUM", propagation_notes="Two independent protocols with different meta-transaction stacks, so the family is about the trust boundary rather than a specific library."),

"ASSET-OR-MARKET-IDENTITY-NOT-VALIDATED": F(
 title="A caller-supplied token, pool, mint or market is accepted without registry validation",
 broken_invariant="Every asset, pool or market a value-bearing operation touches must be resolved from a protocol-controlled registry. An identifier supplied by the caller is a request, not a fact.",
 mechanism="Raydium's deprecated AMM V3 program insufficiently validated LP mint addresses, so a fake LP token bypassed proportion checks and drained ~$1.34M from five inactive pools. Juicebox V3's REVLoans borrowFrom accepted a caller-supplied REVLoanSource struct (.terminal, .token), forging the accounting context so the oracle was skipped and attacker-controlled decimals/balances set the share price. Rhea Finance's attacker pre-created fake token pools on Ref Finance to construct a malicious swap route for its margin engine.",
 mandatory_preconditions=["A value-bearing function accepts a token, pool, market or mint identifier from the caller","No check that the identifier is registered/derived by the protocol","The identifier determines pricing, proportion or destination","Protocol-held value is reachable through it"],
 optional_amplifiers=["Permissionless pool creation on the venue","Deprecated program with weaker validation","Multi-hop routing across arbitrary pools"],
 applicable_protocol_archetypes=["DEX/AMM","DEX aggregator/router","lending with leverage","token launch platform","cross-chain aggregator"],
 static_indicators=["pool/mint/terminal addresses taken as parameters without a registry lookup","PDA/seed derivation not asserted (Solana)","struct parameters carrying accounting context","no allowlist of routable venues"],
 adapter_indicators=["adapter enumerates pools from a factory but the protocol accepts arbitrary pools","adapter routes through third-party venues"],
 runtime_state_indicators=["registry/whitelist empty or permissive","recently created pools reachable by the router","deprecated programs still callable"],
 cross_contract_indicators=["routing venue permits permissionless pool creation while the consumer trusts any pool"],
 decisive_guards=["Registry/factory-derivation check on every identifier (assert factory.getPool(a,b,fee) == suppliedPool, or PDA derivation)","Allowlist of routable venues and assets","Per-hop economic validation, not just endpoint validation"],
 false_positive_killers=["Every identifier derived or verified against the factory/registry (kills the pair)","Routing restricted to an immutable venue allowlist"],
 local_defensive_property="On a fork, create a fake pool/mint and pass it to every identifier-accepting entrypoint; all must revert.",
 evidence_strength="HIGH", propagation_notes="The general prerequisite is composability with permissionless venues: any protocol that routes through, or prices from, a venue where anyone can create a market inherits it."),

"QUOTE-OR-ROUTE-OUTPUT-NOT-BOUND-TO-ASSET": F(
 title="A quoted or aggregated output is applied to a different asset, unit or route than it was computed for",
 broken_invariant="A quantity produced by a quoter or accumulated across a route must be re-bound to the asset, decimals and per-hop economics it describes before it is used to transfer value.",
 mechanism="Kipseli's Base router took the amount from a USDC-only quoter and used it as the raw tokenOut transfer amount without checking the output token matched the quote token; a WETH -> cbBTC path produced a 6-decimal USDC value transferred as 8-decimal cbBTC, so ~0.04 WETH bought ~0.926 cbBTC (~$72.35K). Rhea aggregated expected output across multi-step swaps without accounting for tokens reused across steps, so a constructed route bypassed slippage protection for ~$18.4M. Juicebox skipped the oracle when currency matched the destination and used attacker-controlled decimals and balances.",
 mandatory_preconditions=["A quote, expected-output or aggregate figure is computed in one context and consumed in another","No assertion binding it to the output asset, its decimals, or per-hop reality","The consumed figure sizes a transfer, mint or borrow","Reachable by a caller who supplies the route or path"],
 optional_amplifiers=["Multi-hop routes","Caller-supplied route construction","Assets with differing decimals","Fee-on-transfer tokens in the path"],
 applicable_protocol_archetypes=["DEX aggregator/router","leveraged trading engine","cross-chain aggregator","lending extension","launch platform"],
 static_indicators=["quoter output used directly as a transfer amount","no decimals normalisation between quote and settlement asset","slippage checked only on the aggregate route result","currency-match branches skipping the oracle"],
 adapter_indicators=["adapter references a router/quoter pair","protocol methodology describes multi-hop routing or margin/leverage swaps"],
 runtime_state_indicators=["router supporting arbitrary token pairs while the quoter supports one base asset","no per-hop minimum-out enforcement"],
 cross_contract_indicators=["quoter and settlement contract maintained separately, with differing supported-asset sets"],
 decisive_guards=["Assert quoteToken == outputToken and normalise decimals before transfer","Per-hop minimum-out enforcement, not aggregate-only","Post-swap balance-delta measurement as the authoritative amount"],
 false_positive_killers=["Amount taken from a measured post-transfer balance delta (kills the pair)","Per-hop minimums enforced","Router restricted to assets the quoter supports"],
 local_defensive_property="On a fork, route through an unsupported or mismatched-decimals pair and assert the router reverts rather than transferring a mis-scaled amount.",
 evidence_strength="HIGH", propagation_notes="Produced the largest single included loss of the window (Rhea, $18.4M). Routers and leverage engines that accept caller-constructed routes are the screening surface."),

"INCENTIVE-PER-ADDRESS-NO-SYBIL-COST": F(
 title="A per-address grant is repeatable at negligible cost with fresh addresses",
 broken_invariant="An incentive granted per address must cost the claimant more than it pays, or must be bound to an identity or stake that cannot be cheaply duplicated.",
 mechanism="WUSD.fi / GLOVE granted rewards in the _englove path to addresses holding under 2 GLOVE with no Sybil resistance. Using EIP-7702 helper contracts and a Morpho USDT flash loan, the attacker repeatedly wrapped and unwrapped at least 100 WUSD across fresh addresses, harvesting nearly 2 GLOVE per cycle and dumping into Uniswap V3 for ~$200K of USDC/USDT.",
 mandatory_preconditions=["A reward or bonus is granted per address, per epoch, or on a threshold condition","Creating qualifying addresses is cheap","The reward is immediately liquid","A funded pool or liquid market absorbs the claimed value"],
 optional_amplifiers=["EIP-7702 batching many addresses in one transaction","Flash loans for the qualifying balance","Thin market for the reward token making the incentive large in relative terms"],
 applicable_protocol_archetypes=["stablecoin issuer with incentives","reward distributor","points/airdrop","launchpad","loyalty program"],
 static_indicators=["reward conditions keyed on balanceOf(msg.sender) < threshold","first-time-user bonuses without proof of uniqueness","no per-address lifetime cap"],
 adapter_indicators=["adapter counts an incentive pool as TVL","protocol methodology describes per-user bonuses"],
 runtime_state_indicators=["incentive pool funded and claimable now","reward token thin relative to the pool","many fresh addresses claiming in one block"],
 cross_contract_indicators=["7702 delegation making batch address creation cheap"],
 decisive_guards=["Rewards proportional to stake and time, not per address","Lifetime per-address caps with a global budget","Proof-of-uniqueness or a minimum holding period","Vesting so rewards cannot be dumped in the same transaction"],
 false_positive_killers=["Rewards strictly proportional to time-weighted stake (kills the pair)","Vesting or claim delay prevents same-transaction realisation"],
 local_defensive_property="On a fork, batch N fresh addresses through the qualifying flow in one transaction and assert total reward scales with capital committed, not with address count.",
 evidence_strength="MEDIUM", propagation_notes="SINGLE_EVENT_FAMILY, but EIP-7702 materially lowered the cost of the address-multiplication step, so per-address incentive designs that were previously uneconomic to farm are now in range."),

"AMM-POOL-RATIO-SKEW-EXTRACTION": F(
 title="A pool's own pricing curve can be skewed by flash-funded swaps to extract more than the fee compensates",
 broken_invariant="A pool's invariant and fee schedule must ensure that any round trip through it costs the trader at least the fees, for every reachable ratio, including extreme imbalance.",
 mechanism="Allbridge Core's Solana USDC/USDT pools were skewed by rapid swaps funded with a ~$1.12M Kamino flash loan, draining ~$1.65M. The stable-swap style curve mispriced at extreme imbalance so a round trip was profitable rather than fee-paying.",
 mandatory_preconditions=["The protocol operates its own pricing curve (stable-swap, bonding, or custom)","The curve's output at extreme imbalance is favourable to the trader","Ratio can be moved and restored within one transaction or block","Pool holds LP-owned value"],
 optional_amplifiers=["Flash loans","Low or flat fees","Multiple correlated pools to cycle between","Cross-chain pools sharing one curve"],
 applicable_protocol_archetypes=["DEX/AMM","bridge with liquidity pools","stable-swap","basis trading"],
 static_indicators=["custom invariant implementations","fee independent of imbalance","no imbalance cap or per-block trade-size limit"],
 adapter_indicators=["adapter reads pool balances for a bridge or custom AMM","liquidity concentrated in few pools"],
 runtime_state_indicators=["pool ratio far from balanced","fee parameters flat across the curve","no per-block volume cap"],
 cross_contract_indicators=["the same curve deployed across chains with differing depth"],
 decisive_guards=["Imbalance-scaled fees making extreme-ratio round trips loss-making","Per-block trade-size or ratio-change caps","Curve tested to the boundary with a proof that round trips are non-profitable"],
 false_positive_killers=["Round-trip non-profitability proven across the ratio range (kills the pair)","Standard constant-product with a fee floor"],
 local_defensive_property="On a fork, fuzz round trips at every reachable ratio with flash-scale size; realised profit before gas must never be positive.",
 evidence_strength="MEDIUM", propagation_notes="SINGLE_EVENT_FAMILY. Distinct from the oracle families because the pool is the victim of its own curve rather than a consumer of a manipulated price."),
}
