# -*- coding: utf-8 -*-
"""Mechanism families, part B: remaining high-yield families for protocol screening."""
FAM_B = {

"ACC-DONATION-UNACCOUNTED-BALANCE": dict(
 title="An exchange rate or totalAssets is derived from a raw token balance, so an unaccounted transfer inflates it",
 broken_invariant="A share price, exchange rate or totalAssets must be a function of value the protocol accounted for on entry. Reading a raw balance makes any direct transfer into the accounting boundary an unpriced increase in every holder's claim.",
 mechanism="The rate is computed as (cash + borrows - reserves) / totalSupply, or as sum(balanceOf(component)), where cash is read via balanceOf(address(this)) or a component's balance. A direct transfer into that boundary raises the numerator with no new shares minted. Venus: getCashPrior() reads the vTHE contract's THE balance, so donations lifted the rate 1.03 -> 3.17 and bypassed the supply cap entirely (supply reached 367% of cap). Curve LlamaLend: DolaSavings.stake() donation lifted sDOLA's convertToAssets() 13.79%, and the market used that rate as its oracle. Lazy Summer: an impaired Silo Ark left active in the NAV let the attacker transfer economically worthless but on-chain-par tokens into the still-counted Ark, raising totalAssets() without realizable USDC.",
 mandatory_preconditions=[
   "A rate/NAV/exchange-rate read includes a raw balance of the protocol or a counted component",
   "An unprivileged party can transfer that asset into the accounting boundary (no allowlist on inbound transfers)",
   "The inflated rate is consumed by a value-bearing decision (redeem, borrow-power, liquidation, oracle)",
   "Other holders' claims or third-party positions are exposed to the inflated rate"],
 optional_amplifiers=["Flash liquidity","Long pre-accumulation of the donated asset","Supply-cap bypass because the cap is checked on mint but the rate is not","Impaired asset still carried at book value"],
 applicable_protocol_archetypes=["lending (Compound fork)","CDP","vault/share token (ERC-4626)","yield aggregator","risk curator","liquid staking","basis trading"],
 static_indicators=["getCashPrior()/totalAssets() returning IERC20(x).balanceOf(address(this))","exchangeRateStored = (cash + borrows - reserves)/totalSupply","convertToAssets/pricePerShare with no internally tracked asset counter","supply caps checked at mint but not against the rate"],
 adapter_indicators=["adapter sums balanceOf across strategy/Ark/silo addresses","adapter treats a component vault's share price as authoritative","Compound-fork adapter template (cToken/vToken enumeration)"],
 runtime_state_indicators=["exchange rate materially above 1 and rising without proportional supply growth","market supply exceeding the configured supply cap","components in totalAssets whose underlying market is impaired or halted","donation-shaped Transfer events into the vault/cToken with no matching Mint"],
 cross_contract_indicators=["a counted component is itself an ERC-4626 whose rate is externally manipulable","offboarding partially complete: strategy removed from UI but still in the assets array"],
 decisive_guards=["Internally tracked totalAssets counter incremented only on accounted deposits","Rate floors/ceilings and per-block rate-change caps that revert","Virtual shares/assets offset (ERC-4626 OZ v5 style)","Explicit skim of unaccounted balance to reserves rather than to the rate","Offboarding removes the component from the assets array atomically with pausing it"],
 false_positive_killers=["totalAssets derived from an internal counter, not balanceOf (kills the pair)","Rate is monotonic and rate-limited per block","Inbound transfers to the accounting boundary are rejected or swept to a reserve"],
 local_defensive_property="On a fork, transfer an arbitrary amount of each counted asset directly into every accounting boundary; the share price, exchange rate and derived borrow power must not change.",
 evidence_strength="HIGH",
 propagation_notes="Venus is a Compound-fork lineage defect that was raised in the protocol's own Code4rena audit and disputed at the time, so every unmodified Compound/Venus fork inherits it. Lazy Summer and Curve show the ERC-4626 variant. Because Compound forks and ERC-4626 vaults are the two most-copied templates in DeFi, this family has the widest live prerequisite base of any in the corpus."),

"CALLDATA-CALLER-CONTROLLED-TARGET": dict(
 title="A public entrypoint executes caller-specified target and calldata while the contract holds authority or approvals",
 broken_invariant="A contract that holds allowances, credit delegation or roles must never execute a call whose target and calldata the caller chooses. Its authority may only be spent on calls the contract itself constructs from validated inputs.",
 mechanism="A multicall, router, executor, adapter or 'helper' exposes run(Call[] calls) / execute(target,data) / an unnamed selector taking (address,bytes) and performs target.call(data) or delegatecall. Because the contract is the msg.sender for that inner call, everything it is trusted for is spendable: victims' ERC-20 allowances via transferFrom, ERC-721 setApprovalForAll, Aave credit delegation borrow(), or an arbitrary approval grant. Squid Multicall drained users who approved the multicall instead of the router; a custom sAVAX Aave rebalancer let any caller borrow against the victim's delegated credit; Unistreets' factory custodied launched LP NFTs and accepted injected setApprovalForAll calldata; the third-party SquidRouterModule combined this with a constant-string 'secret' as its only authentication.",
 mandatory_preconditions=[
   "Public/permissionless function accepting a call target and calldata (or an array of them)",
   "The executing contract holds spendable authority: live ERC-20/721 allowances, credit delegation, a role, or custody",
   "No allowlist restricting target/selector, and no binding of the moved value to msg.sender",
   "Reachable without privileged status"],
 optional_amplifiers=["Contract name resembling a well-known safe contract, attracting misdirected approvals","Long-lived unlimited approvals","Module installed into user smart accounts"],
 applicable_protocol_archetypes=["DEX aggregator/router","bridge","smart account module","account abstraction","token launch platform","leveraged staking helper","MEV/keeper contract"],
 static_indicators=["function run/execute/multicall/aggregate taking (address,bytes) or Call[]","low-level .call(data) or delegatecall with unvalidated target","no allowlist mapping for targets or selectors","authentication by comparing to a constant string/hash present in the deployed bytecode"],
 adapter_indicators=["adapter references a Multicall/Executor/Router address distinct from the main router","adapter enumerates helper contracts users may approve"],
 runtime_state_indicators=["non-zero ERC-20 allowances or setApprovalForAll from live EOAs to the executor","credit delegation (DELEGATION_WITH_SIG / approveDelegation) granted to the contract","contract holds custody of NFTs/LP positions it did not create per-user"],
 cross_contract_indicators=["executor address appears in a lending market's delegation registry","executor installed as a Safe module or 7702 delegate"],
 decisive_guards=["Target/selector allowlist enforced on every call","Value moved only from msg.sender (payer bound to caller)","Contract holds no persistent approvals; allowances are per-flow and revoked at the end","Executor cannot be the approval target by construction (separate, non-approvable contract)"],
 false_positive_killers=["Every target is checked against an immutable allowlist (kills the pair)","Contract holds zero live allowances and no delegation (kills exposure)","transferFrom is always from msg.sender"],
 local_defensive_property="On a fork, with a victim account holding a live approval to the contract, prove no permissionless entrypoint can move the victim's tokens.",
 evidence_strength="HIGH",
 propagation_notes="Exposure here is measurable without reading any logic: enumerate live allowances and delegations to each helper address. Approval-bearing helper contracts, not TVL, are the value at risk, so this family routinely applies to protocols whose DefiLlama TVL is small."),

"CALLBACK-UNAUTHENTICATED-CALLER-USES-APPROVALS": dict(
 title="A callback or validation hook moves value from an address it never verified as the flow initiator",
 broken_invariant="When a contract pulls funds during a callback, the payer must be proven to be the initiator of the current flow, and the callback's caller must be proven to be the expected counterparty contract. Neither may be taken from caller-supplied payload.",
 mechanism="A flash-accounting or hook architecture passes a payload through a lock/callback. The callback implements pay() as token.transferFrom(payer, core, amount) with payer, token and amount read straight from that payload, and never asserts payer == lockInitiator. Any caller can therefore nominate a previously-approving victim as payer. Ekubo's v2 extension lost ~$1.4M (~17 WBTC) this way across ~85 transactions. The same shape appears where a swap callback (pancakeV3SwapCallback) on an EIP-7702-delegated account has no caller check, and where an account-abstraction validation phase grants an allowance as a side effect, letting a malicious paymaster harvest it (Lumi/Sodium).",
 mandatory_preconditions=[
   "A callback/hook pulls value using transferFrom or an allowance",
   "The payer/source address comes from caller-supplied payload or is unchecked",
   "The callback does not verify msg.sender is the expected pool/core contract",
   "Live approvals exist from third parties to the callback-implementing contract"],
 optional_amplifiers=["Flash accounting / singleton lock architecture","Router approvals carried over from a prior version","Smart-account delegation (7702) adding callbacks to EOAs"],
 applicable_protocol_archetypes=["DEX/AMM with hooks or flash accounting","router/extension contract","account abstraction","paymaster","leveraged position manager"],
 static_indicators=["pay/uniswapV3SwapCallback/lockAcquired implementations reading payer from calldata","transferFrom(payer,...) where payer is a parameter","callback without require(msg.sender == pool/core)","approve() executed inside validateUserOp or a validation phase"],
 adapter_indicators=["adapter lists extension/hook contracts separately from core","hook or extension addresses that users approve directly"],
 runtime_state_indicators=["live allowances from EOAs to the extension/hook/router","7702 delegation designators on user EOAs pointing at code with public callbacks","core contract's lock state readable and unbound to payer"],
 cross_contract_indicators=["extension trusted by core, but core does not forward the verified initiator","paymaster allowed to spend allowances created during validation"],
 decisive_guards=["require(msg.sender == expectedPool/core) in every callback","payer bound to the lock initiator recorded in transient storage at lock time","allowance granted for exactly one flow and revoked before return","no allowance side effects during validation phases"],
 false_positive_killers=["Callback asserts both caller identity and payer == initiator (kills the pair)","Contract never holds third-party approvals","Payment always uses msg.sender as source"],
 local_defensive_property="On a fork, with a victim approval live, attempt to initiate the lock/callback path nominating the victim as payer; it must revert.",
 evidence_strength="HIGH",
 propagation_notes="Singleton/flash-accounting designs (Uniswap V4-style hooks, Ekubo, Ambient) push payment into callbacks, so the number of live protocols with this shape is growing. Custom third-party extensions, not the audited core, are where the gap appeared."),

"ACC-NAV-SHAREPRICE-MANIPULABLE": dict(
 title="Vault NAV counts positions whose on-chain valuation is inflatable or stale relative to realizable value",
 broken_invariant="totalAssets() must equal value the vault could actually realise now. Any component valued at book, at a manipulable rate, or after economic impairment lets a redeemer convert other depositors' claims into their own.",
 mechanism="The vault sums component valuations. At least one component is (a) an impaired or halted position still carried at par, (b) an externally manipulable share rate, or (c) priced by an oracle that can return zero or a wrong number. The attacker inflates or exploits the mismatch, mints or redeems at the wrong ratio, and extracts the difference from other depositors. Lazy Summer combined an incompletely offboarded Silo Ark with a $65.4M flash loan; Singularity's silent-zero oracle made totalAssets() report ~$100 so a flash deposit minted ~99.99% of shares; Edel inflated a wrapped-token exchange rate ~78x through repeated deposit/borrow loops.",
 mandatory_preconditions=[
   "Share price computed from a multi-component totalAssets()",
   "At least one component's valuation is externally influenceable, stale, or can return an absurd value",
   "Deposit and redeem are both reachable in a short window (same tx or same block)",
   "Other depositors' value is pooled with the attacker's"],
 optional_amplifiers=["Flash loans","Offboarding in progress","Impaired upstream market (e.g. a collapsed strategy)","Zero/near-zero reported totalAssets making share minting cheap"],
 applicable_protocol_archetypes=["yield aggregator","vault/share token","risk curator","structured product","onchain capital allocator","basis trading","indexes"],
 static_indicators=["totalAssets() looping over a strategies/arks array","component valuation via an external convertToAssets or oracle without sanity bounds","no per-block deposit/redeem rate-change cap","no minimum totalAssets floor before share minting"],
 adapter_indicators=["adapter enumerates strategies/arks/silos dynamically","adapter includes addresses of upstream markets that are paused or impaired","risk-curator adapters aggregating third-party vault positions"],
 runtime_state_indicators=["strategies array containing addresses whose upstream market is halted","reported APY/share-price discontinuities","totalAssets small relative to component notional","components whose own share price recently moved sharply"],
 cross_contract_indicators=["vault depends on another protocol's vault token whose rate is donation-inflatable","curator multisig can add components without timelock"],
 decisive_guards=["Per-block share-price change cap that reverts","Deposit and redeem in the same block disallowed or fee-penalised","Component valuation bounded by an independent price with deviation caps","Offboarding atomically removes the component from totalAssets","Minimum totalAssets floor and virtual-share offset"],
 false_positive_killers=["Share price rate-limited per block (kills same-transaction extraction)","Single-asset vault with no external valuation","Withdrawals queued with a delay and priced at settlement"],
 local_defensive_property="On a fork, for each component, force its valuation to zero and to 10x; the vault's mint/redeem must revert or be bounded, never transfer more than the depositor's pro-rata realisable share.",
 evidence_strength="HIGH",
 propagation_notes="The DefiLlama 'Risk Curators' and 'Onchain Capital Allocator' categories exist precisely because curators assemble third-party components into vaults; every added component is a new valuation dependency. Lazy Summer's root cause was an incomplete offboarding process, i.e. an operational failure expressed on-chain, which is invisible to a code-only audit."),

"AUTH-MISSING-ON-VALUE-MOVING-PATH": dict(
 title="A value-moving or configuration-setting function has no access control, or lost it in a refactor",
 broken_invariant="Every function that moves value or rebinds a privileged address must require a role the caller cannot obtain.",
 mechanism="A modifier is absent or was dropped during a refactor. SubQuery's Settings.setContractAddress() lost onlyOwner in a prior refactor, letting anyone install themselves as StakingManager and RewardsDistributor and drain pooled SQT from 272 stakers. Crypto DAO's Pro token exposed vault functions publicly; a permissionlessly-listed YieldCore vault omitted a caller check and was emptied in one call; Gondi V3's Sell-and-Repay bundler bypassed ownership checks on escrowed NFTs.",
 mandatory_preconditions=["A function moves value or sets a privileged address/role","No effective access control on that function","Reachable by an ordinary caller","The contract holds or controls value at call time"],
 optional_amplifiers=["Recent refactor or upgrade","Contract not covered by the latest audit","Permissionless listing so nobody reviews the specific instance"],
 applicable_protocol_archetypes=["any"],
 static_indicators=["external/public state-changing functions with no modifier","setters for manager/distributor/treasury addresses without onlyOwner/role","git history showing a modifier removed","unverified implementation behind a verified proxy"],
 adapter_indicators=["adapter lists per-market or per-vault contracts created permissionlessly","adapter's address list far larger than the audited set"],
 runtime_state_indicators=["role holders that are EOAs","config setters callable in eth_call from an arbitrary address without revert","recently deployed contracts holding value with no audit reference"],
 cross_contract_indicators=["one contract's unguarded setter rebinds an address another contract trusts"],
 decisive_guards=["Role check on every state-changing external function, verified by selector enumeration","Timelock on address-rebinding setters","Automated deployment-time assertion that all setters revert for a random caller"],
 false_positive_killers=["Every value-moving selector reverts for an unprivileged caller in simulation (kills the pair)","Contract holds no value and controls no role"],
 local_defensive_property="Enumerate every external selector on the live implementation and prove, from an unprivileged address on a fork, that each either reverts or cannot move value or authority.",
 evidence_strength="HIGH",
 propagation_notes="Frequently introduced by refactors and by permissionless listing surfaces, where each new instance is unreviewed. Detection is cheap and fully read-only: selector enumeration plus simulated calls from an unprivileged address."),

"PROOF-VERIFICATION-BYPASSED": dict(
 title="A zk, rollup or attestation proof is not required, incompletely verified, or checked against a misconfigured key",
 broken_invariant="A withdrawal or mint gated by a proof must verify that proof against the correct verifying key, over all the public inputs that bind the action, and must reject when any component is absent.",
 mechanism="Observed shapes: a deposit path that accepts entries with no proof at all (Hinkal 'proofless deposit'); minting on forged proofs because proof validity was never enforced (Quicksilver unchecked proof minting); a verifying key misconfigured so forged zkSNARK proofs verify (FOOMCASH); an auxiliary withdrawal script whose key-reset defence could be bypassed while the core circuit stayed sound (HermesVault); incomplete verification logic in a deprecated rollup router (Aztec Connect) and an immutable escape hatch accepting fake rollup proofs with no ownership check (Aztec Bridge).",
 mandatory_preconditions=["A value-releasing path is gated by a proof or attestation","Verification omits a component, uses a wrong/settable key, or the path is reachable without a proof","The releasing contract holds redeemable value","Reachable by an unprivileged caller"],
 optional_amplifiers=["Deprecated/immutable deployment nobody monitors","Privacy design hiding the anomaly","Auxiliary scripts outside the audited circuit"],
 applicable_protocol_archetypes=["privacy pool","rollup/canonical bridge","liquid staking with proof-based mint","cross-chain messaging","gaming with zk claims"],
 static_indicators=["verifier address or verifying key settable post-deployment","public inputs array shorter than the action's binding fields","escape-hatch/emergency withdraw paths with weaker checks","verification result assigned but not required"],
 adapter_indicators=["adapter counts a shielded pool balance it cannot decompose","adapter references a verifier or rollup processor address"],
 runtime_state_indicators=["verifying key hash not matching the published circuit artifact","verifier address recently changed or owned by an EOA","escape-hatch functions still callable on a deprecated deployment"],
 cross_contract_indicators=["prover/attestation registry mutable by a non-timelocked role","multiple verifier generations live simultaneously"],
 decisive_guards=["Verifying key immutable and hash-matched to a published artifact","All action-binding fields present in public inputs","Every release path requires proof verification with no bypass branch","Nullifier consumed before release"],
 false_positive_killers=["Verifying key immutable and attested (kills the misconfiguration shape)","No alternative release path exists (enumerate selectors)"],
 local_defensive_property="On a fork, submit an empty proof, a proof for different public inputs, and a proof under a foreign key; every release path must revert.",
 evidence_strength="HIGH",
 propagation_notes="Two of the seven were deprecated Aztec deployments, which is why this family overlaps heavily with UPGRADE-OLD-DEPLOYMENT-LIVE-AUTHORITY: proof systems are hardest to fix once immutable."),

"UPGRADE-INITIALIZER-REACHABLE-LIVE": dict(
 title="An initializer remains callable on a live deployment",
 broken_invariant="After deployment, no caller may (re)establish ownership, admin, or implementation wiring. Initialization state must be provably consumed.",
 mechanism="An initializer is unprotected, or the initialized flag lives in a slot the deployment never wrote. Aurellion's Diamond (EIP-2535) had an owner set but OpenZeppelin's _initialized slot still 0, so initialize(address) could be called again; the attacker took ownership, used diamondCut to add a facet exposing pullERC20/sweep, and drained wallets that had approved the diamond. Renegade's V1 dark-pool proxy had an unprotected initializer plus a version counter left out of sync by an April 2025 migration, enabling malicious logic and a delegatecall drain of 27 ERC-20s.",
 mandatory_preconditions=["An initializer/reinitializer is reachable on the live proxy or facet","The initialized flag is unset, or the version counter allows re-entry","Initialization can grant ownership or rewire implementation","The deployment holds value or live approvals"],
 optional_amplifiers=["Diamond/beacon architecture with many facets","A migration that changed the initializer scheme","Live unlimited approvals to the proxy"],
 applicable_protocol_archetypes=["governance-controlled proxy","diamond","beacon proxy","any upgradeable deployment"],
 static_indicators=["initialize()/reinitializer(n) external without initializer modifier","custom initialization flags not matching the OZ slot","diamondCut callable by owner with no timelock"],
 adapter_indicators=["adapter references proxy addresses across several deployment generations","adapter's addresses include facets or beacons"],
 runtime_state_indicators=["ERC-1967 _initialized slot reads 0 on a live proxy","implementation slot changed recently","live approvals to the proxy","owner is an EOA"],
 cross_contract_indicators=["beacon controls many child proxies, so one initializer covers all children","proxy admin equals deployer EOA"],
 decisive_guards=["initializer/reinitializer modifiers with the flag asserted non-zero post-deploy","Deployment-time assertion that re-initialization reverts","diamondCut and upgrade behind a timelock"],
 false_positive_killers=["Simulated re-initialization reverts (kills the pair)","Contract is non-upgradeable and holds no approvals"],
 local_defensive_property="Read the initialization slot on every live proxy/facet and simulate re-initialization from an unprivileged address; it must revert.",
 evidence_strength="HIGH",
 propagation_notes="Directly observable read-only: one storage read of the ERC-1967/OZ initialized slot plus one simulated call per proxy. Beacon architectures multiply the blast radius across every child."),

"GOV-CHEAP-CONTROL-NO-TIMELOCK": dict(
 title="Voting power is cheaply acquirable and executes without a delay long enough to respond",
 broken_invariant="The cost of acquiring decisive voting power must exceed the value governance controls, and execution must be separated from passage by a delay long enough for holders to exit or a guardian to veto.",
 mechanism="Low float, low quorum, or a small total supply lets an attacker buy control on the open market (or borrow it) and pass a proposal that mints, upgrades or transfers. With no timelock, passage and execution occur before anyone can react. Token of Power: >50% of a 16,384-token supply acquired with Tornado-funded capital, minted billions and drained 944 WETH from a Balancer V1 pool in a single transaction. BonkDAO: ~$4M of BONK bought to pass BIP-76 and move ~$20M of treasury. BarnBridge: DAO control used to upgrade a proxy to a malicious implementation and drain ~$776K through pre-existing approvals from ~50 addresses. Moonwell/Moonriver: ~$1,800 bought 40M MFAM and passed an initial vote in 11 minutes targeting seven markets, the comptroller and the oracle.",
 mandatory_preconditions=["On-chain governance can move value, mint, or upgrade","Decisive voting power is acquirable at a cost below the controlled value","No timelock, or a timelock shorter than a realistic response window","Reachable without stolen credentials"],
 optional_amplifiers=["Governance token borrowable or flash-loanable","Snapshot at proposal time rather than a historical block","Proxy upgrade in scope of governance","Live user approvals to governance-upgradeable contracts"],
 applicable_protocol_archetypes=["governance-controlled proxy","DAO treasury","lending with governance-set parameters","token with on-chain governance"],
 static_indicators=["Governor with quorum as a small fraction of supply","no TimelockController between passage and execution","proposal threshold denominated in tokens rather than value","upgrade/mint in the executor's capability set"],
 adapter_indicators=["adapter lists a treasury address controlled by governance","governance-owned proxy admin appears in the adapter's address set"],
 runtime_state_indicators=["market cost to reach quorum far below treasury + controlled TVL","timelock delay zero or minimal","recent proposals passing with tiny participation","live approvals to governance-upgradeable spenders"],
 cross_contract_indicators=["governance executor holds MINTER or PROXY_ADMIN on funded contracts","the same executor controls the oracle"],
 decisive_guards=["Timelock long enough for exit, with a guardian veto","Quorum and threshold scaled to controlled value, not token count","Voting power snapshot at a historical block, defeating same-block acquisition","Upgrade and mint removed from governance's reach or separately gated"],
 false_positive_killers=["Timelock plus an active guardian with veto (kills execution speed)","Cost to acquire quorum exceeds controlled value by a wide margin","Governance cannot upgrade or mint"],
 local_defensive_property="Compute, from live market depth, the capital required to reach quorum, and compare it with treasury plus TVL plus the value reachable through approvals; the ratio is the finding.",
 evidence_strength="HIGH",
 propagation_notes="Ranking must use value controlled through approvals and roles, not just treasury size: BarnBridge's treasury was not the target, users' pre-existing approvals were."),

"ACC-ZERO-SUPPLY-INFLATION": dict(
 title="Share math has an unguarded zero-supply or near-zero-supply branch",
 broken_invariant="The first depositor must not be able to set an arbitrary asset-per-share ratio, and no operation may drive supply low enough to restore that branch.",
 mechanism="With totalSupply == 0 and totalAssets == 0, a 1-wei deposit mints 1 share; a direct transfer of a large amount then makes each share worth that amount, so later depositors round to zero shares and the attacker redeems the pool. The same branch is reachable later if supply can be burned to near zero (Thetanuts' legacy vault reduced supply to near zero, then drained via redemption math). dTRINITY's dLEND took this on a live Ethereum deployment, leaving ~$257K of bad debt.",
 mandatory_preconditions=["Share minting formula divides by totalSupply or totalAssets with a zero branch","An unprivileged party can be the first depositor, or can drive supply to near zero","Assets can be transferred in without minting shares","A later depositor's funds are exposed to the manipulated ratio"],
 optional_amplifiers=["Permissionless market/vault creation","Newly deployed vaults with no seed","Flash liquidity"],
 applicable_protocol_archetypes=["vault/share token (ERC-4626)","lending market creation","options vault","yield aggregator"],
 static_indicators=["shares = assets * totalSupply / totalAssets with no virtual offset","no minimum initial deposit or dead-shares mint","permissionless createVault/createMarket"],
 adapter_indicators=["adapter enumerates factory-created vaults/markets","adapter includes very recently created vaults with tiny TVL"],
 runtime_state_indicators=["live vaults/markets with totalSupply == 0 or dust supply","factory able to create new markets permissionlessly","no dead-shares balance at address(0) or address(1)"],
 cross_contract_indicators=["factory deploys vaults without seeding them","router auto-lists new markets"],
 decisive_guards=["Virtual shares/assets offset (OZ ERC-4626 v5)","Non-zero minimum initial shares burned to a dead address at creation","Factory seeds every market at deploy time","Minimum deposit floor"],
 false_positive_killers=["Dead shares minted at creation (kills the pair)","Vault creation is permissioned and every vault is seeded","Virtual offset present in the deployed bytecode"],
 local_defensive_property="On a fork, for every vault with dust or zero supply, attempt the 1-wei-plus-donation sequence and assert a later depositor's shares are proportional.",
 evidence_strength="HIGH",
 propagation_notes="Still occurring on brand-new deployments in 2026 despite being a decade-old pattern, because factory-created markets are seeded by users rather than by the factory. Screen every factory's most recently created, least-funded children."),

"LIQUIDATION-ON-MANIPULABLE-VALUATION": dict(
 title="Liquidation or mark price is movable by the party who profits from the liquidation",
 broken_invariant="A position may be liquidated only on a valuation that the liquidator cannot move, and the discount captured must not exceed the cost of moving the price.",
 mechanism="The health/mark computation reads a price the liquidator can move in the same transaction (thin AMM, mark price on a shallow market, or a share rate inflatable by donation). The attacker forces positions unhealthy and captures the liquidation discount, or profits from a hedged position on the other side. 42DAO pushed a median oracle's BTCB price abnormally low to force BTCB-vault liquidations (~$915K, BLC depegged >99%). Cascade accumulated longs in a low-liquidity market to push the mark price and liquidate CLS shorts (~$1.34M). Curve LlamaLend forced positions into soft liquidation, then donated to lift the sDOLA rate so they became hard-liquidatable (27 borrowers, ~$10.9M debt, ~$822K borrower equity lost). Aave's CAPO misparameterisation liquidated 34 healthy positions.",
 mandatory_preconditions=["Liquidation eligibility derived from a price/rate readable at call time","That price is movable by the liquidator, or misparameterised","A liquidation incentive or a hedged position makes the move profitable","Live borrower positions exist near the threshold"],
 optional_amplifiers=["Flash loans","Soft-liquidation (LLAMMA) bands amplifying the effect","Thin mark-price market","Large notional near the threshold"],
 applicable_protocol_archetypes=["lending","CDP","derivatives/perpetuals","basis trading","RWA lending"],
 static_indicators=["health factor computed from a spot or convertToAssets read","no deviation bound or grace period between price update and liquidation","liquidation bonus fixed and large relative to venue depth"],
 adapter_indicators=["adapter shows collateral concentrated in one asset","adapter lists markets whose collateral has thin external liquidity"],
 runtime_state_indicators=["large borrow notional clustered near the liquidation threshold","collateral asset whose deepest venue depth is small relative to that notional","no liquidation circuit breaker or cooldown"],
 cross_contract_indicators=["the price source is a pool the liquidator can trade in the same transaction","the mark price venue is the protocol's own book"],
 decisive_guards=["Liquidation prices from a deep aggregated feed with a deviation cap","Grace period / cooldown between a large price move and liquidation eligibility","Liquidation size caps per block","Circuit breaker on abnormal price deltas"],
 false_positive_killers=["Deviation-capped, independently sourced price plus a grace period (kills the pair)","Liquidations rate-limited per block","Collateral only in deep assets with caps sized to depth"],
 local_defensive_property="On a fork, execute the largest flash-funded move available on each pricing venue and assert that no position becomes liquidatable beyond the configured deviation bound.",
 evidence_strength="HIGH",
 propagation_notes="Distinct from the borrow-side oracle families because the guards differ: liquidation-side needs grace periods, size caps and circuit breakers, not just a better price. Two of the five did not steal protocol funds at all; the loss fell on borrowers, which loss-only rankings miss."),
}
